UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 0 WHERE ActivitytemplatId = 1
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 1 WHERE ActivitytemplatId = 2
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 0 WHERE ActivitytemplatId = 3
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 1 WHERE ActivitytemplatId = 4
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 1 WHERE ActivitytemplatId = 5
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 0 WHERE ActivitytemplatId = 6
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 1 WHERE ActivitytemplatId = 7
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 0 WHERE ActivitytemplatId = 8
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 1 WHERE ActivitytemplatId = 9
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 1 WHERE ActivitytemplatId = 10
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 1 WHERE ActivitytemplatId = 11
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 0 WHERE ActivitytemplatId = 12
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 0 WHERE ActivitytemplatId = 13
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = 0 WHERE ActivitytemplatId = 14
UPDATE [LookUps].[Activitytemplate] SET [HasYears] = NULL WHERE ActivitytemplatId = 15