//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.AnnouncementResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayInputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayInputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.AnnouncementResources.DisplayInputs", typeof(DisplayInputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات النشطة فقط.
        /// </summary>
        public static string ActiveAnnouncements {
            get {
                return ResourceManager.GetString("ActiveAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف النشاط.
        /// </summary>
        public static string ActivityDescription {
            get {
                return ResourceManager.GetString("ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجهة.
        /// </summary>
        public static string AgencyName {
            get {
                return ResourceManager.GetString("AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الإعلانات.
        /// </summary>
        public static string AllAnnouncement {
            get {
                return ResourceManager.GetString("AllAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلانات قوائم الموردين.
        /// </summary>
        public static string AllAnnouncementTemplate {
            get {
                return ResourceManager.GetString("AllAnnouncementTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الإعلان.
        /// </summary>
        public static string AnnouncementDetails {
            get {
                return ResourceManager.GetString("AnnouncementDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الإعلان عن المنافسة.
        /// </summary>
        public static string AnnouncementDuration {
            get {
                return ResourceManager.GetString("AnnouncementDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الإعلان.
        /// </summary>
        public static string AnnouncementName {
            get {
                return ResourceManager.GetString("AnnouncementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الإعلان عن المنافسة.
        /// </summary>
        public static string AnnouncementPeriod {
            get {
                return ResourceManager.GetString("AnnouncementPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نشر الإعلان.
        /// </summary>
        public static string AnnouncementPublishDate {
            get {
                return ResourceManager.GetString("AnnouncementPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتائج الإعلان.
        /// </summary>
        public static string AnnouncementResult {
            get {
                return ResourceManager.GetString("AnnouncementResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الإعلان.
        /// </summary>
        public static string AnnouncementStatus {
            get {
                return ResourceManager.GetString("AnnouncementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم القائمة.
        /// </summary>
        public static string AnnouncementSupplierTemplateName {
            get {
                return ResourceManager.GetString("AnnouncementSupplierTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل القائمة.
        /// </summary>
        public static string AnnouncementTemplateDetails {
            get {
                return ResourceManager.GetString("AnnouncementTemplateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع القائمة.
        /// </summary>
        public static string AnnouncementTemplateSuppliersListType {
            get {
                return ResourceManager.GetString("AnnouncementTemplateSuppliersListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الإعلان.
        /// </summary>
        public static string AnnouncementType {
            get {
                return ResourceManager.GetString("AnnouncementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعتمدة من قبل.
        /// </summary>
        public static string ApprovedByText {
            get {
                return ResourceManager.GetString("ApprovedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المناطق.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتمدت بواسطة.
        /// </summary>
        public static string AuditedBy {
            get {
                return ResourceManager.GetString("AuditedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفرع.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند التأكيد سيتم إلغاء القائمة ولن تكون سارية للاستعمال.
        /// </summary>
        public static string CancelAnnouncementSupplierTemplate {
            get {
                return ResourceManager.GetString("CancelAnnouncementSupplierTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب التوقف عن استخدام القائمة.
        /// </summary>
        public static string CancelationReason {
            get {
                return ResourceManager.GetString("CancelationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجال التصنيف.
        /// </summary>
        public static string CategoryField {
            get {
                return ResourceManager.GetString("CategoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السجل التجاري.
        /// </summary>
        public static string CommercialRegistrationNumber {
            get {
                return ResourceManager.GetString("CommercialRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعمال الإنشاء.
        /// </summary>
        public static string ConstructionWorks {
            get {
                return ResourceManager.GetString("ConstructionWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدول.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء/تحرير إعلان.
        /// </summary>
        public static string CreateAnnouncement {
            get {
                return ResourceManager.GetString("CreateAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء/تحرير إعلان قائمة الموردين.
        /// </summary>
        public static string CreateAnnouncementTemplate {
            get {
                return ResourceManager.GetString("CreateAnnouncementTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشأت بواسطة.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاءت عن طريق.
        /// </summary>
        public static string CreatedByText {
            get {
                return ResourceManager.GetString("CreatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الإنشاء.
        /// </summary>
        public static string CreationDetails {
            get {
                return ResourceManager.GetString("CreationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التواريخ واماكن التنفيذ.
        /// </summary>
        public static string DateLocation {
            get {
                return ResourceManager.GetString("DateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواعيد.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف استخدامات القائمة.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ السريان للقائمة.
        /// </summary>
        public static string EffectiveListDate {
            get {
                return ResourceManager.GetString("EffectiveListDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت انتهاء القائمة.
        /// </summary>
        public static string EffectiveListTime {
            get {
                return ResourceManager.GetString("EffectiveListTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان التنفيذ.
        /// </summary>
        public static string ExecutionLocation {
            get {
                return ResourceManager.GetString("ExecutionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند التأكيد سيتم إعادة نشر اعلان للتسجيل بالقائمة لجميع الموردين.
        /// </summary>
        public static string ExtendAnnouncementSupplierTemplateConfirmationMessage {
            get {
                return ResourceManager.GetString("ExtendAnnouncementSupplierTemplateConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمديد سريان القائمة .
        /// </summary>
        public static string ExtendAnnouncementTemplate {
            get {
                return ResourceManager.GetString("ExtendAnnouncementTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عامة.
        /// </summary>
        public static string GeneralList {
            get {
                return ResourceManager.GetString("GeneralList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الجهة الحكومية.
        /// </summary>
        public static string GovAgencyInfo {
            get {
                return ResourceManager.GetString("GovAgencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات المنتهية فقط.
        /// </summary>
        public static string InactiveAnnounements {
            get {
                return ResourceManager.GetString("InactiveAnnounements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان التنفيذ.
        /// </summary>
        public static string InsideKSA {
            get {
                return ResourceManager.GetString("InsideKSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف القائمة.
        /// </summary>
        public static string IntroAboutAnnouncementTemplate {
            get {
                return ResourceManager.GetString("IntroAboutAnnouncementTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف عن المنافسة.
        /// </summary>
        public static string IntroAboutTender {
            get {
                return ResourceManager.GetString("IntroAboutTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد مدة السريان للقائمة.
        /// </summary>
        public static string IsEffectiveList {
            get {
                return ResourceManager.GetString("IsEffectiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب مرفقات.
        /// </summary>
        public static string IsRequiredAttachmentToJoinList {
            get {
                return ResourceManager.GetString("IsRequiredAttachmentToJoinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب انضمام للمنافسة.
        /// </summary>
        public static string JoinAnnouncement {
            get {
                return ResourceManager.GetString("JoinAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد طلبات الانضمام.
        /// </summary>
        public static string JoinRequestsCount {
            get {
                return ResourceManager.GetString("JoinRequestsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة طلبات الانضمام.
        /// </summary>
        public static string JoinRequestsList {
            get {
                return ResourceManager.GetString("JoinRequestsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر موعد لتقديم طلبات الانضمام للمنافسة.
        /// </summary>
        public static string LastJoinDate {
            get {
                return ResourceManager.GetString("LastJoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعمال الصيانة والتشغيل.
        /// </summary>
        public static string MaintenanceOperationActions {
            get {
                return ResourceManager.GetString("MaintenanceOperationActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعلاناتى.
        /// </summary>
        public static string MyAnnouncements {
            get {
                return ResourceManager.GetString("MyAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات النشطة.
        /// </summary>
        public static string OnlyActiveAnnouncements {
            get {
                return ResourceManager.GetString("OnlyActiveAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات المنتهية.
        /// </summary>
        public static string OnlyEndedAnnouncements {
            get {
                return ResourceManager.GetString("OnlyEndedAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاصة.
        /// </summary>
        public static string PrivateList {
            get {
                return ResourceManager.GetString("PrivateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النشر.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسلوب الشراء بناء على نتائج الإعلان.
        /// </summary>
        public static string PurchaseMethodBasedOnAnnouncement {
            get {
                return ResourceManager.GetString("PurchaseMethodBasedOnAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم المرجعى للإعلان.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجال التصنيف والانشطة.
        /// </summary>
        public static string RelationStep {
            get {
                return ResourceManager.GetString("RelationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة طلب الانضمام.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات المطلوبة.
        /// </summary>
        public static string RequiredAttachment {
            get {
                return ResourceManager.GetString("RequiredAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط الازمة للانضمام للقائمة.
        /// </summary>
        public static string RequirementConditionsToJoinList {
            get {
                return ResourceManager.GetString("RequirementConditionsToJoinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملفات الداعمة.
        /// </summary>
        public static string SupportingDocuments {
            get {
                return ResourceManager.GetString("SupportingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آلية تجديد القائمة.
        /// </summary>
        public static string TemplateExtendMechanism {
            get {
                return ResourceManager.GetString("TemplateExtendMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنشطة المنافسة.
        /// </summary>
        public static string TenderActivities {
            get {
                return ResourceManager.GetString("TenderActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشاط المنافسة.
        /// </summary>
        public static string TenderActivity {
            get {
                return ResourceManager.GetString("TenderActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المنافسة.
        /// </summary>
        public static string TenderTypeName {
            get {
                return ResourceManager.GetString("TenderTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعلانات تحت الانشاء.
        /// </summary>
        public static string UnderOperationAnnouncements {
            get {
                return ResourceManager.GetString("UnderOperationAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحرير إعلان قائمة الموردين.
        /// </summary>
        public static string UpdateAnnouncementSupplierTemplate {
            get {
                return ResourceManager.GetString("UpdateAnnouncementSupplierTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند التأكيد سيتم تحديث القائمة.
        /// </summary>
        public static string UpdateAnnouncementSupplierTemplateConfirmationMessage {
            get {
                return ResourceManager.GetString("UpdateAnnouncementSupplierTemplateConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سحب طلب الإنضمام.
        /// </summary>
        public static string WithdrawAnnouncementRequest {
            get {
                return ResourceManager.GetString("WithdrawAnnouncementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
