//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.AnnouncementResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.AnnouncementResources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار الأنشطة.
        /// </summary>
        public static string ActivityIdRequired {
            get {
                return ResourceManager.GetString("ActivityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال بيانات الجهة الحكومية.
        /// </summary>
        public static string AgencyRequired {
            get {
                return ResourceManager.GetString("AgencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعلان غير معتمد.
        /// </summary>
        public static string AnnoucementNotApproved {
            get {
                return ResourceManager.GetString("AnnoucementNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الإعلان يجب ان تكون رقم صحيح اكبر من 9 و اقل من 1000.
        /// </summary>
        public static string AnnouncementPeriodRange {
            get {
                return ResourceManager.GetString("AnnouncementPeriodRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الإعلان يجب ان تكون رقم صحيح أكبر من أو يساوى 10 و أقل من 1000.
        /// </summary>
        public static string AnnouncementPeriodRangeForDirectPurchase {
            get {
                return ResourceManager.GetString("AnnouncementPeriodRangeForDirectPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الإعلان يجب ان تكون رقم صحيح أكبر من أو يساوى 20 و أقل من 1000.
        /// </summary>
        public static string AnnouncementPeriodRangeForLimitedTender {
            get {
                return ResourceManager.GetString("AnnouncementPeriodRangeForLimitedTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال المرفقات المطلوبة.
        /// </summary>
        public static string AnnouncementRequiredAttachment {
            get {
                return ResourceManager.GetString("AnnouncementRequiredAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد انتهت فترة الاعلان.
        /// </summary>
        public static string AnnouncmentDateExpired {
            get {
                return ResourceManager.GetString("AnnouncmentDateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال سبب التوقف عن استخدام القائمة.
        /// </summary>
        public static string CancelationReasonAnnouncementRequired {
            get {
                return ResourceManager.GetString("CancelationReasonAnnouncementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار أعمال الإنشاء.
        /// </summary>
        public static string ConstructionWorkRequired {
            get {
                return ResourceManager.GetString("ConstructionWorkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال تاريخ سريان القائمة.
        /// </summary>
        public static string EffectiveListDateRequired {
            get {
                return ResourceManager.GetString("EffectiveListDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال عنوان الجهة.
        /// </summary>
        public static string EnterAgencyAddress {
            get {
                return ResourceManager.GetString("EnterAgencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال الفاكس.
        /// </summary>
        public static string EnterFax {
            get {
                return ResourceManager.GetString("EnterFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال رقم الهاتف.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل البيانات.
        /// </summary>
        public static string EnterRequiredData {
            get {
                return ResourceManager.GetString("EnterRequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار نوع المنافسة.
        /// </summary>
        public static string EnterTenderTypes {
            get {
                return ResourceManager.GetString("EnterTenderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال البريد الإلكتروني بشكل صحيح.
        /// </summary>
        public static string MailValidation {
            get {
                return ResourceManager.GetString("MailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال اسم الإعلان.
        /// </summary>
        public static string PleaseEnterAnnouncementName {
            get {
                return ResourceManager.GetString("PleaseEnterAnnouncementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال مدة الإعلان.
        /// </summary>
        public static string PleaseEnterAnnouncementPeriod {
            get {
                return ResourceManager.GetString("PleaseEnterAnnouncementPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال اسم القائمة.
        /// </summary>
        public static string PleaseEnterAnnouncementSupplierTemplateName {
            get {
                return ResourceManager.GetString("PleaseEnterAnnouncementSupplierTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال وصف استخدامات القائمة.
        /// </summary>
        public static string PleaseEnterDescriptions {
            get {
                return ResourceManager.GetString("PleaseEnterDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال تعريف القائمة.
        /// </summary>
        public static string PleaseEnterIntroAboutAnnouncementTemplate {
            get {
                return ResourceManager.GetString("PleaseEnterIntroAboutAnnouncementTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال الشروط اللازمة للانضمام للقائمة.
        /// </summary>
        public static string PleaseEnterRequirementConditionsToJoinList {
            get {
                return ResourceManager.GetString("PleaseEnterRequirementConditionsToJoinList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال آلية تجديد القائمة.
        /// </summary>
        public static string PleaseEnterTemplateExtendeMechanism {
            get {
                return ResourceManager.GetString("PleaseEnterTemplateExtendeMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال تعريف عن المنافسة .
        /// </summary>
        public static string PleaseEnterTenderIntro {
            get {
                return ResourceManager.GetString("PleaseEnterTenderIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إختيار النشاط.
        /// </summary>
        public static string PleaseSelectActivities {
            get {
                return ResourceManager.GetString("PleaseSelectActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إختيار المناطق.
        /// </summary>
        public static string PleaseSelectAreas {
            get {
                return ResourceManager.GetString("PleaseSelectAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إختيار الدول.
        /// </summary>
        public static string PleaseSelectCountries {
            get {
                return ResourceManager.GetString("PleaseSelectCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد طلب تحت الاجراء.
        /// </summary>
        public static string ThierIsRequestUnderProcessing {
            get {
                return ResourceManager.GetString("ThierIsRequestUnderProcessing", resourceCulture);
            }
        }
    }
}
