//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFileService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServicePerson", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServicePerson : object
    {

        private string AdditionalNoField;

        private System.Nullable<System.DateTime> BirthDateField;

        private string BirthDateHijriField;

        private string BuildingNoField;

        private int CityIDField;

        private string CityNameField;

        private string CityTelephoneCodeField;

        private string ContactEmailField;

        private string ContactMobileField;

        private string ContactTelephoneField;

        private string CountryIDField;

        private string CountryNameField;

        private int DistrictIDField;

        private string DistrictNameField;

        private System.Nullable<System.DateTime> ExpiryDateField;

        private string FirstNameField;

        private string FormalIdentityNumberField;

        private string FullDistrictField;

        private string GenderField;

        private bool HasWaselAccountField;

        private string InterContactMobileField;

        private string InterContactTelephoneField;

        private string IssueAuthorityField;

        private System.Nullable<System.DateTime> IssueDateField;

        private string IssuePlaceField;

        private string LastNameField;

        private int LegalStatusField;

        private string NationalityIDField;

        private string NationalityNameField;

        private string POBoxField;

        private System.Guid PersonGUIDField;

        private string PersonImageField;

        private int PersonTypeField;

        private string PostalCodeField;

        private string SecondNameField;

        private string StreetNameField;

        private string TelephoneCodeIDField;

        private string ThirdNameField;

        private string UnitNoField;

        private EFileService.EFileServiceBlocked UserBlackListedServicesField;

        private string UserIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalNo
        {
            get
            {
                return this.AdditionalNoField;
            }
            set
            {
                this.AdditionalNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDateHijri
        {
            get
            {
                return this.BirthDateHijriField;
            }
            set
            {
                this.BirthDateHijriField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNo
        {
            get
            {
                return this.BuildingNoField;
            }
            set
            {
                this.BuildingNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                this.CityNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityTelephoneCode
        {
            get
            {
                return this.CityTelephoneCodeField;
            }
            set
            {
                this.CityTelephoneCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail
        {
            get
            {
                return this.ContactEmailField;
            }
            set
            {
                this.ContactEmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactMobile
        {
            get
            {
                return this.ContactMobileField;
            }
            set
            {
                this.ContactMobileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTelephone
        {
            get
            {
                return this.ContactTelephoneField;
            }
            set
            {
                this.ContactTelephoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryID
        {
            get
            {
                return this.CountryIDField;
            }
            set
            {
                this.CountryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictID
        {
            get
            {
                return this.DistrictIDField;
            }
            set
            {
                this.DistrictIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName
        {
            get
            {
                return this.DistrictNameField;
            }
            set
            {
                this.DistrictNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormalIdentityNumber
        {
            get
            {
                return this.FormalIdentityNumberField;
            }
            set
            {
                this.FormalIdentityNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullDistrict
        {
            get
            {
                return this.FullDistrictField;
            }
            set
            {
                this.FullDistrictField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWaselAccount
        {
            get
            {
                return this.HasWaselAccountField;
            }
            set
            {
                this.HasWaselAccountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterContactMobile
        {
            get
            {
                return this.InterContactMobileField;
            }
            set
            {
                this.InterContactMobileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterContactTelephone
        {
            get
            {
                return this.InterContactTelephoneField;
            }
            set
            {
                this.InterContactTelephoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueAuthority
        {
            get
            {
                return this.IssueAuthorityField;
            }
            set
            {
                this.IssueAuthorityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IssueDate
        {
            get
            {
                return this.IssueDateField;
            }
            set
            {
                this.IssueDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuePlace
        {
            get
            {
                return this.IssuePlaceField;
            }
            set
            {
                this.IssuePlaceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LegalStatus
        {
            get
            {
                return this.LegalStatusField;
            }
            set
            {
                this.LegalStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityID
        {
            get
            {
                return this.NationalityIDField;
            }
            set
            {
                this.NationalityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityName
        {
            get
            {
                return this.NationalityNameField;
            }
            set
            {
                this.NationalityNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBox
        {
            get
            {
                return this.POBoxField;
            }
            set
            {
                this.POBoxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonGUID
        {
            get
            {
                return this.PersonGUIDField;
            }
            set
            {
                this.PersonGUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonImage
        {
            get
            {
                return this.PersonImageField;
            }
            set
            {
                this.PersonImageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonType
        {
            get
            {
                return this.PersonTypeField;
            }
            set
            {
                this.PersonTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName
        {
            get
            {
                return this.SecondNameField;
            }
            set
            {
                this.SecondNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneCodeID
        {
            get
            {
                return this.TelephoneCodeIDField;
            }
            set
            {
                this.TelephoneCodeIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThirdName
        {
            get
            {
                return this.ThirdNameField;
            }
            set
            {
                this.ThirdNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNo
        {
            get
            {
                return this.UnitNoField;
            }
            set
            {
                this.UnitNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EFileService.EFileServiceBlocked UserBlackListedServices
        {
            get
            {
                return this.UserBlackListedServicesField;
            }
            set
            {
                this.UserBlackListedServicesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceBlocked", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceBlocked : object
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceContactOfficer", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceContactOfficer : object
    {

        private string AdditionalNoField;

        private System.Nullable<System.DateTime> BirthDateField;

        private string BirthDateHijriField;

        private string BuildingNoField;

        private string CityNameField;

        private string CityTelephoneCodeField;

        private string ContactEmailField;

        private string ContactMobileField;

        private System.Collections.Generic.KeyValuePair<string, string> ContactOfficerCRsField;

        private string ContactTelephoneField;

        private string CountryNameField;

        private string DistrictNameField;

        private System.Nullable<System.DateTime> ExpiryDateField;

        private string FirstNameField;

        private string FormalIdentityNumberField;

        private string GenderField;

        private bool HasWaselAccountField;

        private string InterContactMobileField;

        private string InterContactTelephoneField;

        private string IssueAuthorityField;

        private System.Nullable<System.DateTime> IssueDateField;

        private string IssuePlaceField;

        private string LastNameField;

        private int LegalStatusField;

        private string POBoxField;

        private System.Guid PersonGUIDField;

        private string PersonImageField;

        private string PostalCodeField;

        private string SecondNameField;

        private string StreetNameField;

        private string TelephoneCodeIDField;

        private string ThirdNameField;

        private string UnitNoField;

        private EFileService.EFileServiceBlocked UserBlackListedServicesField;

        private string UserIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalNo
        {
            get
            {
                return this.AdditionalNoField;
            }
            set
            {
                this.AdditionalNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDateHijri
        {
            get
            {
                return this.BirthDateHijriField;
            }
            set
            {
                this.BirthDateHijriField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNo
        {
            get
            {
                return this.BuildingNoField;
            }
            set
            {
                this.BuildingNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                this.CityNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityTelephoneCode
        {
            get
            {
                return this.CityTelephoneCodeField;
            }
            set
            {
                this.CityTelephoneCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail
        {
            get
            {
                return this.ContactEmailField;
            }
            set
            {
                this.ContactEmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactMobile
        {
            get
            {
                return this.ContactMobileField;
            }
            set
            {
                this.ContactMobileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string> ContactOfficerCRs
        {
            get
            {
                return this.ContactOfficerCRsField;
            }
            set
            {
                this.ContactOfficerCRsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTelephone
        {
            get
            {
                return this.ContactTelephoneField;
            }
            set
            {
                this.ContactTelephoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName
        {
            get
            {
                return this.DistrictNameField;
            }
            set
            {
                this.DistrictNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormalIdentityNumber
        {
            get
            {
                return this.FormalIdentityNumberField;
            }
            set
            {
                this.FormalIdentityNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWaselAccount
        {
            get
            {
                return this.HasWaselAccountField;
            }
            set
            {
                this.HasWaselAccountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterContactMobile
        {
            get
            {
                return this.InterContactMobileField;
            }
            set
            {
                this.InterContactMobileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterContactTelephone
        {
            get
            {
                return this.InterContactTelephoneField;
            }
            set
            {
                this.InterContactTelephoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueAuthority
        {
            get
            {
                return this.IssueAuthorityField;
            }
            set
            {
                this.IssueAuthorityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IssueDate
        {
            get
            {
                return this.IssueDateField;
            }
            set
            {
                this.IssueDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssuePlace
        {
            get
            {
                return this.IssuePlaceField;
            }
            set
            {
                this.IssuePlaceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LegalStatus
        {
            get
            {
                return this.LegalStatusField;
            }
            set
            {
                this.LegalStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBox
        {
            get
            {
                return this.POBoxField;
            }
            set
            {
                this.POBoxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonGUID
        {
            get
            {
                return this.PersonGUIDField;
            }
            set
            {
                this.PersonGUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonImage
        {
            get
            {
                return this.PersonImageField;
            }
            set
            {
                this.PersonImageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName
        {
            get
            {
                return this.SecondNameField;
            }
            set
            {
                this.SecondNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneCodeID
        {
            get
            {
                return this.TelephoneCodeIDField;
            }
            set
            {
                this.TelephoneCodeIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThirdName
        {
            get
            {
                return this.ThirdNameField;
            }
            set
            {
                this.ThirdNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNo
        {
            get
            {
                return this.UnitNoField;
            }
            set
            {
                this.UnitNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EFileService.EFileServiceBlocked UserBlackListedServices
        {
            get
            {
                return this.UserBlackListedServicesField;
            }
            set
            {
                this.UserBlackListedServicesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceAddress", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceAddress : object
    {

        private string AdditionalNumberField;

        private string BuildingNumberField;

        private int CityIDField;

        private string CountryIDField;

        private bool IsWaselField;

        private string NeighborhoodField;

        private int NeighborhoodIDField;

        private string POBoxField;

        private string StreetField;

        private string UnitNumberField;

        private string UserIDField;

        private string ZipCodeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalNumber
        {
            get
            {
                return this.AdditionalNumberField;
            }
            set
            {
                this.AdditionalNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNumber
        {
            get
            {
                return this.BuildingNumberField;
            }
            set
            {
                this.BuildingNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryID
        {
            get
            {
                return this.CountryIDField;
            }
            set
            {
                this.CountryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWasel
        {
            get
            {
                return this.IsWaselField;
            }
            set
            {
                this.IsWaselField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Neighborhood
        {
            get
            {
                return this.NeighborhoodField;
            }
            set
            {
                this.NeighborhoodField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NeighborhoodID
        {
            get
            {
                return this.NeighborhoodIDField;
            }
            set
            {
                this.NeighborhoodIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBox
        {
            get
            {
                return this.POBoxField;
            }
            set
            {
                this.POBoxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNumber
        {
            get
            {
                return this.UnitNumberField;
            }
            set
            {
                this.UnitNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AccessTokenModel", Namespace = "http://schemas.datacontract.org/2004/07/EFile.WebUI.Models")]
    public partial class AccessTokenModel : object
    {

        private string ClientTokenField;

        private string UserTokenField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientToken
        {
            get
            {
                return this.ClientTokenField;
            }
            set
            {
                this.ClientTokenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserToken
        {
            get
            {
                return this.UserTokenField;
            }
            set
            {
                this.UserTokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServicePersonProfile", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServicePersonProfile : object
    {

        private string Base64ImageField;

        private string ContentTypeField;

        private string CountryIDField;

        private string EducationIDField;

        private string EmailField;

        private string MobileField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64Image
        {
            get
            {
                return this.Base64ImageField;
            }
            set
            {
                this.Base64ImageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType
        {
            get
            {
                return this.ContentTypeField;
            }
            set
            {
                this.ContentTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryID
        {
            get
            {
                return this.CountryIDField;
            }
            set
            {
                this.CountryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationID
        {
            get
            {
                return this.EducationIDField;
            }
            set
            {
                this.EducationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServicePersonAddress", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServicePersonAddress : object
    {

        private string AdditionalNoField;

        private string BuildingNoField;

        private string CityIDField;

        private string CountryIDField;

        private string DistrictIDField;

        private System.Nullable<bool> HasWaselAccountField;

        private string LatitudeField;

        private string LongtitudeField;

        private string POBoxField;

        private string PostalCodeField;

        private string StreetNameField;

        private string TitleField;

        private string UnitNoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalNo
        {
            get
            {
                return this.AdditionalNoField;
            }
            set
            {
                this.AdditionalNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNo
        {
            get
            {
                return this.BuildingNoField;
            }
            set
            {
                this.BuildingNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryID
        {
            get
            {
                return this.CountryIDField;
            }
            set
            {
                this.CountryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictID
        {
            get
            {
                return this.DistrictIDField;
            }
            set
            {
                this.DistrictIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasWaselAccount
        {
            get
            {
                return this.HasWaselAccountField;
            }
            set
            {
                this.HasWaselAccountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longtitude
        {
            get
            {
                return this.LongtitudeField;
            }
            set
            {
                this.LongtitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBox
        {
            get
            {
                return this.POBoxField;
            }
            set
            {
                this.POBoxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNo
        {
            get
            {
                return this.UnitNoField;
            }
            set
            {
                this.UnitNoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceDelegated", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceDelegated : object
    {

        private string DelegateTypeField;

        private bool HasReferenceField;

        private string ReferenceNumberField;

        private string RoleIDField;

        private string RoleNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelegateType
        {
            get
            {
                return this.DelegateTypeField;
            }
            set
            {
                this.DelegateTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasReference
        {
            get
            {
                return this.HasReferenceField;
            }
            set
            {
                this.HasReferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceDelegation", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceDelegation : object
    {

        private EFileService.EFileServiceDelegateInfo[] BeneficiariesField;

        private EFileService.EFileServiceDelegateInfo[] DelegatorsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EFileService.EFileServiceDelegateInfo[] Beneficiaries
        {
            get
            {
                return this.BeneficiariesField;
            }
            set
            {
                this.BeneficiariesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EFileService.EFileServiceDelegateInfo[] Delegators
        {
            get
            {
                return this.DelegatorsField;
            }
            set
            {
                this.DelegatorsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceDelegateInfo", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceDelegateInfo : object
    {

        private string DelegateTypeField;

        private string FullNameField;

        private string NIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelegateType
        {
            get
            {
                return this.DelegateTypeField;
            }
            set
            {
                this.DelegateTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NID
        {
            get
            {
                return this.NIDField;
            }
            set
            {
                this.NIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceDelegationDetails", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceDelegationDetails : object
    {

        private string BeneficiaryNIDField;

        private string BeneficiaryNameField;

        private System.DateTime CreationDateField;

        private EFileService.EFileServiceDelegated[] DelegatedReferencesField;

        private string DelegatorNIDField;

        private string DelegatorNameField;

        private System.DateTime ExpiryDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryNID
        {
            get
            {
                return this.BeneficiaryNIDField;
            }
            set
            {
                this.BeneficiaryNIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryName
        {
            get
            {
                return this.BeneficiaryNameField;
            }
            set
            {
                this.BeneficiaryNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EFileService.EFileServiceDelegated[] DelegatedReferences
        {
            get
            {
                return this.DelegatedReferencesField;
            }
            set
            {
                this.DelegatedReferencesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelegatorNID
        {
            get
            {
                return this.DelegatorNIDField;
            }
            set
            {
                this.DelegatorNIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelegatorName
        {
            get
            {
                return this.DelegatorNameField;
            }
            set
            {
                this.DelegatorNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceBlackListed", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceBlackListed : object
    {

        private bool HasReferenceField;

        private string ReferenceNumberField;

        private string RoleIDField;

        private string RoleNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasReference
        {
            get
            {
                return this.HasReferenceField;
            }
            set
            {
                this.HasReferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceRole", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceRole : object
    {

        private string DelegateTypeField;

        private bool HasReferenceField;

        private string RoleIDField;

        private string RoleNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelegateType
        {
            get
            {
                return this.DelegateTypeField;
            }
            set
            {
                this.DelegateTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasReference
        {
            get
            {
                return this.HasReferenceField;
            }
            set
            {
                this.HasReferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceCountry", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceCountry : object
    {

        private string AreaCodeField;

        private string CountryIDField;

        private string CountryNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode
        {
            get
            {
                return this.AreaCodeField;
            }
            set
            {
                this.AreaCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryID
        {
            get
            {
                return this.CountryIDField;
            }
            set
            {
                this.CountryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceCity", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceCity : object
    {

        private int CityIDField;

        private string CityNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                this.CityNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EFileServiceDistrict", Namespace = "http://schemas.datacontract.org/2004/07/EFile.Core.DTO")]
    public partial class EFileServiceDistrict : object
    {

        private int DistrictIDField;

        private string DistrictNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictID
        {
            get
            {
                return this.DistrictIDField;
            }
            set
            {
                this.DistrictIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName
        {
            get
            {
                return this.DistrictNameField;
            }
            set
            {
                this.DistrictNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PasswordRecoveryWay", Namespace = "http://schemas.datacontract.org/2004/07/EFile.WebUI.Helpers")]
    public enum PasswordRecoveryWay : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ChangePasswordModel", Namespace = "http://schemas.datacontract.org/2004/07/EFile.WebUI.Models")]
    public partial class ChangePasswordModel : object
    {

        private string ConfirmPasswordField;

        private string NewPasswordField;

        private string OldPasswordField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmPassword
        {
            get
            {
                return this.ConfirmPasswordField;
            }
            set
            {
                this.ConfirmPasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldPassword
        {
            get
            {
                return this.OldPasswordField;
            }
            set
            {
                this.OldPasswordField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "EFileService.IEFileService")]
    public interface IEFileService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetPersonByUserIDandClientID", ReplyAction = "http://tempuri.org/IEFileService/GetPersonByUserIDandClientIDResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByUserIDandClientIDAsync(string userId, string clientId, string clientPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetPersonByUserID", ReplyAction = "http://tempuri.org/IEFileService/GetPersonByUserIDResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByUserIDAsync(string userId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetPersonByNID", ReplyAction = "http://tempuri.org/IEFileService/GetPersonByNIDResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByNIDAsync(string nid, string clientId, string clientPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetPersonByFIN", ReplyAction = "http://tempuri.org/IEFileService/GetPersonByFINResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByFINAsync(string nid, string clientId, string clientPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/CheckPersonStatus", ReplyAction = "http://tempuri.org/IEFileService/CheckPersonStatusResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServicePerson> CheckPersonStatusAsync(string nid, string clientId, string clientPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetPerson", ReplyAction = "http://tempuri.org/IEFileService/GetPersonResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonAsync(string nid);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetContactOfficerInfo", ReplyAction = "http://tempuri.org/IEFileService/GetContactOfficerInfoResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceContactOfficer> GetContactOfficerInfoAsync(string userAccessToken, string clientId, string clientPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetPersonAddressByNID", ReplyAction = "http://tempuri.org/IEFileService/GetPersonAddressByNIDResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceAddress> GetPersonAddressByNIDAsync(string nid, string clientId, string clientPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/Authenticated", ReplyAction = "http://tempuri.org/IEFileService/AuthenticatedResponse")]
        System.Threading.Tasks.Task<EFileService.AccessTokenModel> AuthenticatedAsync(string clientId, string clientPassword, string NID, string password);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetUsernameByAccessToken", ReplyAction = "http://tempuri.org/IEFileService/GetUsernameByAccessTokenResponse")]
        System.Threading.Tasks.Task<string> GetUsernameByAccessTokenAsync(string userAccessToken);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/CheckToken", ReplyAction = "http://tempuri.org/IEFileService/CheckTokenResponse")]
        System.Threading.Tasks.Task<bool> CheckTokenAsync(EFileService.AccessTokenModel accessToken);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/CheckUserToken", ReplyAction = "http://tempuri.org/IEFileService/CheckUserTokenResponse")]
        System.Threading.Tasks.Task<bool> CheckUserTokenAsync(string userAccessToken, string clientId, string clientPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/IsAuthenticated", ReplyAction = "http://tempuri.org/IEFileService/IsAuthenticatedResponse")]
        System.Threading.Tasks.Task<bool> IsAuthenticatedAsync(string userAccessToken, string clientId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/UpdatePersonInfo", ReplyAction = "http://tempuri.org/IEFileService/UpdatePersonInfoResponse")]
        System.Threading.Tasks.Task<bool> UpdatePersonInfoAsync(EFileService.AccessTokenModel accessToken, EFileService.EFileServicePersonProfile personProfile);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/UpdatePersonAddress", ReplyAction = "http://tempuri.org/IEFileService/UpdatePersonAddressResponse")]
        System.Threading.Tasks.Task<bool> UpdatePersonAddressAsync(EFileService.AccessTokenModel accessToken, EFileService.EFileServicePersonAddress personAddress);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetDelegatedReferencesByServiceID", ReplyAction = "http://tempuri.org/IEFileService/GetDelegatedReferencesByServiceIDResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceDelegated[]> GetDelegatedReferencesByServiceIDAsync(string nid, string clientId, string childClientId, string serviceId, string crNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetDelegatedReferences", ReplyAction = "http://tempuri.org/IEFileService/GetDelegatedReferencesResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceDelegated[]> GetDelegatedReferencesAsync(string nid, string clientId, string clientSecret, string delegatorNID, string crNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetAllDelegationInfo", ReplyAction = "http://tempuri.org/IEFileService/GetAllDelegationInfoResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceDelegation> GetAllDelegationInfoAsync(string nid, string clientId, string clientSecret);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetAllDelegationInfoByCrNumber", ReplyAction = "http://tempuri.org/IEFileService/GetAllDelegationInfoByCrNumberResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceDelegation> GetAllDelegationInfoByCrNumberAsync(string nid, string clientId, string clientSecret, string crNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetAllBeneficiariesByCrNumber", ReplyAction = "http://tempuri.org/IEFileService/GetAllBeneficiariesByCrNumberResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceDelegationDetails[]> GetAllBeneficiariesByCrNumberAsync(string crNumber, string clientId, string clientSecret);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/SendSMS", ReplyAction = "http://tempuri.org/IEFileService/SendSMSResponse")]
        System.Threading.Tasks.Task<bool> SendSMSAsync(string clientId, string otp, string nid);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetBlackListedServicesByServiceID", ReplyAction = "http://tempuri.org/IEFileService/GetBlackListedServicesByServiceIDResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceBlackListed[]> GetBlackListedServicesByServiceIDAsync(string nid, string clientId, string serviceId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetRolesByClientID", ReplyAction = "http://tempuri.org/IEFileService/GetRolesByClientIDResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceRole[]> GetRolesByClientIDAsync(string clientId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetUserRoles", ReplyAction = "http://tempuri.org/IEFileService/GetUserRolesResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceRole[]> GetUserRolesAsync(string nid, string clientId, string childClientId, string serviceId, string crNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetCountries", ReplyAction = "http://tempuri.org/IEFileService/GetCountriesResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceCountry[]> GetCountriesAsync(string clientId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetCities", ReplyAction = "http://tempuri.org/IEFileService/GetCitiesResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceCity[]> GetCitiesAsync(string clientId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/GetDistricts", ReplyAction = "http://tempuri.org/IEFileService/GetDistrictsResponse")]
        System.Threading.Tasks.Task<EFileService.EFileServiceDistrict[]> GetDistrictsAsync(string clientId, int cityId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/Logout", ReplyAction = "http://tempuri.org/IEFileService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(string accessToken);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/Login", ReplyAction = "http://tempuri.org/IEFileService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string clientId, string clientSecret, string NID, string password);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/PasswordRecovery", ReplyAction = "http://tempuri.org/IEFileService/PasswordRecoveryResponse")]
        System.Threading.Tasks.Task<bool> PasswordRecoveryAsync(string nid, string clientId, string clientPassword, EFileService.PasswordRecoveryWay passwordRecoveryWay);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/ChangePersonPassword", ReplyAction = "http://tempuri.org/IEFileService/ChangePersonPasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangePersonPasswordAsync(EFileService.AccessTokenModel accessToken, EFileService.ChangePasswordModel changePassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/ChangePersonPasswordByAccessToken", ReplyAction = "http://tempuri.org/IEFileService/ChangePersonPasswordByAccessTokenResponse")]
        System.Threading.Tasks.Task<bool> ChangePersonPasswordByAccessTokenAsync(string userAccessToken, string oldPassword, string newPassword);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEFileService/AuthenticateByAbsherMobile", ReplyAction = "http://tempuri.org/IEFileService/AuthenticateByAbsherMobileResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateByAbsherMobileAsync(string userName, string clientId, string clientPassword);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IEFileServiceChannel : EFileService.IEFileService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class EFileServiceClient : System.ServiceModel.ClientBase<EFileService.IEFileService>, EFileService.IEFileService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public EFileServiceClient() :
                base(EFileServiceClient.GetDefaultBinding(), EFileServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IEFileService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EFileServiceClient(EndpointConfiguration endpointConfiguration) :
                base(EFileServiceClient.GetBindingForEndpoint(endpointConfiguration), EFileServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EFileServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(EFileServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EFileServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(EFileServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByUserIDandClientIDAsync(string userId, string clientId, string clientPassword)
        {
            return base.Channel.GetPersonByUserIDandClientIDAsync(userId, clientId, clientPassword);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByUserIDAsync(string userId)
        {
            return base.Channel.GetPersonByUserIDAsync(userId);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByNIDAsync(string nid, string clientId, string clientPassword)
        {
            return base.Channel.GetPersonByNIDAsync(nid, clientId, clientPassword);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonByFINAsync(string nid, string clientId, string clientPassword)
        {
            return base.Channel.GetPersonByFINAsync(nid, clientId, clientPassword);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServicePerson> CheckPersonStatusAsync(string nid, string clientId, string clientPassword)
        {
            return base.Channel.CheckPersonStatusAsync(nid, clientId, clientPassword);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServicePerson> GetPersonAsync(string nid)
        {
            return base.Channel.GetPersonAsync(nid);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceContactOfficer> GetContactOfficerInfoAsync(string userAccessToken, string clientId, string clientPassword)
        {
            return base.Channel.GetContactOfficerInfoAsync(userAccessToken, clientId, clientPassword);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceAddress> GetPersonAddressByNIDAsync(string nid, string clientId, string clientPassword)
        {
            return base.Channel.GetPersonAddressByNIDAsync(nid, clientId, clientPassword);
        }

        public System.Threading.Tasks.Task<EFileService.AccessTokenModel> AuthenticatedAsync(string clientId, string clientPassword, string NID, string password)
        {
            return base.Channel.AuthenticatedAsync(clientId, clientPassword, NID, password);
        }

        public System.Threading.Tasks.Task<string> GetUsernameByAccessTokenAsync(string userAccessToken)
        {
            return base.Channel.GetUsernameByAccessTokenAsync(userAccessToken);
        }

        public System.Threading.Tasks.Task<bool> CheckTokenAsync(EFileService.AccessTokenModel accessToken)
        {
            return base.Channel.CheckTokenAsync(accessToken);
        }

        public System.Threading.Tasks.Task<bool> CheckUserTokenAsync(string userAccessToken, string clientId, string clientPassword)
        {
            return base.Channel.CheckUserTokenAsync(userAccessToken, clientId, clientPassword);
        }

        public System.Threading.Tasks.Task<bool> IsAuthenticatedAsync(string userAccessToken, string clientId)
        {
            return base.Channel.IsAuthenticatedAsync(userAccessToken, clientId);
        }

        public System.Threading.Tasks.Task<bool> UpdatePersonInfoAsync(EFileService.AccessTokenModel accessToken, EFileService.EFileServicePersonProfile personProfile)
        {
            return base.Channel.UpdatePersonInfoAsync(accessToken, personProfile);
        }

        public System.Threading.Tasks.Task<bool> UpdatePersonAddressAsync(EFileService.AccessTokenModel accessToken, EFileService.EFileServicePersonAddress personAddress)
        {
            return base.Channel.UpdatePersonAddressAsync(accessToken, personAddress);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceDelegated[]> GetDelegatedReferencesByServiceIDAsync(string nid, string clientId, string childClientId, string serviceId, string crNumber)
        {
            return base.Channel.GetDelegatedReferencesByServiceIDAsync(nid, clientId, childClientId, serviceId, crNumber);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceDelegated[]> GetDelegatedReferencesAsync(string nid, string clientId, string clientSecret, string delegatorNID, string crNumber)
        {
            return base.Channel.GetDelegatedReferencesAsync(nid, clientId, clientSecret, delegatorNID, crNumber);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceDelegation> GetAllDelegationInfoAsync(string nid, string clientId, string clientSecret)
        {
            return base.Channel.GetAllDelegationInfoAsync(nid, clientId, clientSecret);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceDelegation> GetAllDelegationInfoByCrNumberAsync(string nid, string clientId, string clientSecret, string crNumber)
        {
            return base.Channel.GetAllDelegationInfoByCrNumberAsync(nid, clientId, clientSecret, crNumber);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceDelegationDetails[]> GetAllBeneficiariesByCrNumberAsync(string crNumber, string clientId, string clientSecret)
        {
            return base.Channel.GetAllBeneficiariesByCrNumberAsync(crNumber, clientId, clientSecret);
        }

        public System.Threading.Tasks.Task<bool> SendSMSAsync(string clientId, string otp, string nid)
        {
            return base.Channel.SendSMSAsync(clientId, otp, nid);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceBlackListed[]> GetBlackListedServicesByServiceIDAsync(string nid, string clientId, string serviceId)
        {
            return base.Channel.GetBlackListedServicesByServiceIDAsync(nid, clientId, serviceId);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceRole[]> GetRolesByClientIDAsync(string clientId)
        {
            return base.Channel.GetRolesByClientIDAsync(clientId);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceRole[]> GetUserRolesAsync(string nid, string clientId, string childClientId, string serviceId, string crNumber)
        {
            return base.Channel.GetUserRolesAsync(nid, clientId, childClientId, serviceId, crNumber);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceCountry[]> GetCountriesAsync(string clientId)
        {
            return base.Channel.GetCountriesAsync(clientId);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceCity[]> GetCitiesAsync(string clientId)
        {
            return base.Channel.GetCitiesAsync(clientId);
        }

        public System.Threading.Tasks.Task<EFileService.EFileServiceDistrict[]> GetDistrictsAsync(string clientId, int cityId)
        {
            return base.Channel.GetDistrictsAsync(clientId, cityId);
        }

        public System.Threading.Tasks.Task<bool> LogoutAsync(string accessToken)
        {
            return base.Channel.LogoutAsync(accessToken);
        }

        public System.Threading.Tasks.Task<string> LoginAsync(string clientId, string clientSecret, string NID, string password)
        {
            return base.Channel.LoginAsync(clientId, clientSecret, NID, password);
        }

        public System.Threading.Tasks.Task<bool> PasswordRecoveryAsync(string nid, string clientId, string clientPassword, EFileService.PasswordRecoveryWay passwordRecoveryWay)
        {
            return base.Channel.PasswordRecoveryAsync(nid, clientId, clientPassword, passwordRecoveryWay);
        }

        public System.Threading.Tasks.Task<bool> ChangePersonPasswordAsync(EFileService.AccessTokenModel accessToken, EFileService.ChangePasswordModel changePassword)
        {
            return base.Channel.ChangePersonPasswordAsync(accessToken, changePassword);
        }

        public System.Threading.Tasks.Task<bool> ChangePersonPasswordByAccessTokenAsync(string userAccessToken, string oldPassword, string newPassword)
        {
            return base.Channel.ChangePersonPasswordByAccessTokenAsync(userAccessToken, oldPassword, newPassword);
        }

        public System.Threading.Tasks.Task<bool> AuthenticateByAbsherMobileAsync(string userName, string clientId, string clientPassword)
        {
            return base.Channel.AuthenticateByAbsherMobileAsync(userName, clientId, clientPassword);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IEFileService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.AuthenticationScheme = System.Net.AuthenticationSchemes.None;

                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;

                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IEFileService))
            {
                return new System.ServiceModel.EndpointAddress("https://efilepp.mci.gov.sa/WServices/EFileService.svc/WServices/EFileService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EFileServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IEFileService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EFileServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IEFileService);
        }

        public enum EndpointConfiguration
        {

            WSHttpBinding_IEFileService,
        }
    }
}
