//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.OfferResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.OfferResources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يوجد عنصر بديل بالفعل.
        /// </summary>
        public static string AlternativeItemExist
        {
            get
            {
                return ResourceManager.GetString("AlternativeItemExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to متضامن او قائد تضامن فى عرض اخر لنفس المنافسة.
        /// </summary>
        public static string AppliedBefore
        {
            get
            {
                return ResourceManager.GetString("AppliedBefore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إرفاق المرفقات قبل الحفظ.
        /// </summary>
        public static string ApplyOfferAttachmentsDataIssue
        {
            get
            {
                return ResourceManager.GetString("ApplyOfferAttachmentsDataIssue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال أسعار الأصناف قبل الحفظ.
        /// </summary>
        public static string ApplyOfferDataIssue
        {
            get
            {
                return ResourceManager.GetString("ApplyOfferDataIssue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال شهادة تصنيف واحدة علي الأقل.
        /// </summary>
        public static string AtLeastOneClassification
        {
            get
            {
                return ResourceManager.GetString("AtLeastOneClassification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال ضمان بنكى واحد علي الأقل.
        /// </summary>
        public static string AtLeastOneGuarantee
        {
            get
            {
                return ResourceManager.GetString("AtLeastOneGuarantee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون قيمة المزايدة أكبر من صفر.
        /// </summary>
        public static string BiddingValueMustBeGreaterThanZero
        {
            get
            {
                return ResourceManager.GetString("BiddingValueMustBeGreaterThanZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to قيمة المزايدة يجب أن تكون أقل من أخر مزايدة.
        /// </summary>
        public static string BiddingValueMustBeLessThanLastBidding
        {
            get
            {
                return ResourceManager.GetString("BiddingValueMustBeLessThanLastBidding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك قبول  او رفض دعوة التضامن.
        /// </summary>
        public static string CanNotAcceptCombinedInvitation
        {
            get
            {
                return ResourceManager.GetString("CanNotAcceptCombinedInvitation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to السعر لا بد ان يكون اكبر من صفر.
        /// </summary>
        public static string CannotInsertZeroInPrice
        {
            get
            {
                return ResourceManager.GetString("CannotInsertZeroInPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لذلك لا يمكن تعديل جدول الكميات . هذا العرض محذوف أو غير فعال.
        /// </summary>
        public static string CanNotUpdateDeletedOfferTable
        {
            get
            {
                return ResourceManager.GetString("CanNotUpdateDeletedOfferTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء التواصل مع مدقق البيانات.
        /// </summary>
        public static string CheckWithAuditor
        {
            get
            {
                return ResourceManager.GetString("CheckWithAuditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء رفع خطاب التضامن.
        /// </summary>
        public static string CombinationLetter
        {
            get
            {
                return ResourceManager.GetString("CombinationLetter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم اللجنة موجود من قبل.
        /// </summary>
        public static string CommitteeNameExist
        {
            get
            {
                return ResourceManager.GetString("CommitteeNameExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اللجنة غير موجودة.
        /// </summary>
        public static string CommitteeNotFound
        {
            get
            {
                return ResourceManager.GetString("CommitteeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ يجب أن يكون أكبر من تاريخ اليوم.
        /// </summary>
        public static string DateLessThanToday
        {
            get
            {
                return ResourceManager.GetString("DateLessThanToday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يكون مبلغ الخصم أكبر من السعر.
        /// </summary>
        public static string DiscountAmountLargerThanPrice
        {
            get
            {
                return ResourceManager.GetString("DiscountAmountLargerThanPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الايميل موجود بالفعل.
        /// </summary>
        public static string EmailExist
        {
            get
            {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال قيمة الضمان البنكى.
        /// </summary>
        public static string EnterBankGuaranteeValue
        {
            get
            {
                return ResourceManager.GetString("EnterBankGuaranteeValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة ايميل.
        /// </summary>
        public static string EnterEmail
        {
            get
            {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار ملف.
        /// </summary>
        public static string EnterFile
        {
            get
            {
                return ResourceManager.GetString("EnterFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال حقل درجة التقييم المالي..
        /// </summary>
        public static string EnterFinancialWeight
        {
            get
            {
                return ResourceManager.GetString("EnterFinancialWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال رقم الضمان البنكى.
        /// </summary>
        public static string EnterGuaranteeNumber
        {
            get
            {
                return ResourceManager.GetString("EnterGuaranteeNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال حقل الملاحظات..
        /// </summary>
        public static string EnterNotes
        {
            get
            {
                return ResourceManager.GetString("EnterNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة رقم الجوال.
        /// </summary>
        public static string EnterPhone
        {
            get
            {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال قيمة للسعر.
        /// </summary>
        public static string EnterPrice
        {
            get
            {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال جدول كميات على الأقل.
        /// </summary>
        public static string EnterQuantitiesTable
        {
            get
            {
                return ResourceManager.GetString("EnterQuantitiesTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال عنصر واحد على الأقل فى جدول الكميات.
        /// </summary>
        public static string EnterQuantitiesTableItem
        {
            get
            {
                return ResourceManager.GetString("EnterQuantitiesTableItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال إسم الجدول.
        /// </summary>
        public static string EnterTableName
        {
            get
            {
                return ResourceManager.GetString("EnterTableName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال حقل درجة التقييم الفني.
        /// </summary>
        public static string EnterTechnicalWeight
        {
            get
            {
                return ResourceManager.GetString("EnterTechnicalWeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لذلك لا يمكنك تعديل جدول الكميات . العرض يجب أن يكون منشأ مسبقا.
        /// </summary>
        public static string EstablishOfferToUpdateTable
        {
            get
            {
                return ResourceManager.GetString("EstablishOfferToUpdateTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الخصم لا يمكن أن يكون أقل من صفر.
        /// </summary>
        public static string MinimumValueIsZero
        {
            get
            {
                return ResourceManager.GetString("MinimumValueIsZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء مراجعة البيانات والمحاولة مرة اخرى.
        /// </summary>
        public static string ModelDataError
        {
            get
            {
                return ResourceManager.GetString("ModelDataError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to غير فعال (محذوف).
        /// </summary>
        public static string NotActiveDeleted
        {
            get
            {
                return ResourceManager.GetString("NotActiveDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to العرض لجدول الكميات :.
        /// </summary>
        public static string OfferForTable
        {
            get
            {
                return ResourceManager.GetString("OfferForTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يوجد تاريخ لخطاب العرض.
        /// </summary>
        public static string OfferLetterDateMustHaveAValue
        {
            get
            {
                return ResourceManager.GetString("OfferLetterDateMustHaveAValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يوجد رقم  لخطاب العرض.
        /// </summary>
        public static string OfferLetterNumberMustHaveAValue
        {
            get
            {
                return ResourceManager.GetString("OfferLetterNumberMustHaveAValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لذلك لا يمكنك إرسال العرض حيث أن الحالة يجب أن تكون منشأ.
        /// </summary>
        public static string OfferNotEstablishedForOffer
        {
            get
            {
                return ResourceManager.GetString("OfferNotEstablishedForOffer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to العرض غير موجود.
        /// </summary>
        public static string OfferNotExist
        {
            get
            {
                return ResourceManager.GetString("OfferNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لذلك لا يمكنك إرسال العرض حيث أن الحالة يجب أن تكون مستلم.
        /// </summary>
        public static string OfferNotRecievedForOffer
        {
            get
            {
                return ResourceManager.GetString("OfferNotRecievedForOffer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حاله العرض او التقييم الفنى غير متاح.
        /// </summary>
        public static string OfferStatusOrTechnicalEvaluationNotExist
        {
            get
            {
                return ResourceManager.GetString("OfferStatusOrTechnicalEvaluationNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون العرض مطابق فنيا.
        /// </summary>
        public static string OfferTechnicalCheckMustBeIdentical
        {
            get
            {
                return ResourceManager.GetString("OfferTechnicalCheckMustBeIdentical", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء مراجعة المعلومات التالية :.
        /// </summary>
        public static string PleaseCheckBusinessErrors
        {
            get
            {
                return ResourceManager.GetString("PleaseCheckBusinessErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اختر بنك.
        /// </summary>
        public static string SelectBank
        {
            get
            {
                return ResourceManager.GetString("SelectBank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار حالة العرض.
        /// </summary>
        public static string SelectOfferStatus
        {
            get
            {
                return ResourceManager.GetString("SelectOfferStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار التقييم الفنى.
        /// </summary>
        public static string SelectTechnicalEvaluation
        {
            get
            {
                return ResourceManager.GetString("SelectTechnicalEvaluation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هل تأكد عملية ارسال الملفات ادناه كعرض مقدم على المنافسة؟.
        /// </summary>
        public static string SendOfferFilesConfirm
        {
            get
            {
                return ResourceManager.GetString("SendOfferFilesConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية يجب أن يكون أقل من تاريخ النهاية.
        /// </summary>
        public static string StartDateGreaterThanEndDate
        {
            get
            {
                return ResourceManager.GetString("StartDateGreaterThanEndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to في حالة وجود محضر ترسية مرفوع مسبقا سيتم استبداله بالملف الجديد عند الحفظ.
        /// </summary>
        public static string TarsiaReportFile
        {
            get
            {
                return ResourceManager.GetString("TarsiaReportFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المنافسة غير موجودة.
        /// </summary>
        public static string TenderNotExist
        {
            get
            {
                return ResourceManager.GetString("TenderNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خطا فى الارسال.
        /// </summary>
        public static string TenderSentFailed
        {
            get
            {
                return ResourceManager.GetString("TenderSentFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع، الرجاء المحاولة مرة اخرى.
        /// </summary>
        public static string UnexpectedError
        {
            get
            {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
