//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.BranchResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayInputs
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayInputs()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.BranchResources.DisplayInputs", typeof(DisplayInputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إضافة عنوان.
        /// </summary>
        public static string AddAddress
        {
            get
            {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إضافة فرع.
        /// </summary>
        public static string AddBranch
        {
            get
            {
                return ResourceManager.GetString("AddBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم العنوان.
        /// </summary>
        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to العناوين.
        /// </summary>
        public static string AddressList
        {
            get
            {
                return ResourceManager.GetString("AddressList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم العنوان.
        /// </summary>
        public static string AddressName
        {
            get
            {
                return ResourceManager.GetString("AddressName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نوع العنوان.
        /// </summary>
        public static string AddressType
        {
            get
            {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الجهة الحكومية.
        /// </summary>
        public static string AgencyName
        {
            get
            {
                return ResourceManager.GetString("AgencyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اعتماد ترسية المنافسة لصاحب الصلاحية.
        /// </summary>
        public static string ApproveTenderAwarding
        {
            get
            {
                return ResourceManager.GetString("ApproveTenderAwarding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعيين اللجان.
        /// </summary>
        public static string AssignCommittees
        {
            get
            {
                return ResourceManager.GetString("AssignCommittees", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدم جديد.
        /// </summary>
        public static string AssignUsers
        {
            get
            {
                return ResourceManager.GetString("AssignUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعيين مستخدم.
        /// </summary>
        public static string AssignUserToBranchOrCommitte
        {
            get
            {
                return ResourceManager.GetString("AssignUserToBranchOrCommitte", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مدقق.
        /// </summary>
        public static string Auditor
        {
            get
            {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معلومات الفرع.
        /// </summary>
        public static string BranchDetails
        {
            get
            {
                return ResourceManager.GetString("BranchDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        public static string Branches
        {
            get
            {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إسم الفرع.
        /// </summary>
        public static string BranchName
        {
            get
            {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم لجنة فحص العروض.
        /// </summary>
        public static string CheckAgencyName
        {
            get
            {
                return ResourceManager.GetString("CheckAgencyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رمز المدينة.
        /// </summary>
        public static string CityCode
        {
            get
            {
                return ResourceManager.GetString("CityCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إسم اللجنة.
        /// </summary>
        public static string CommitteeName
        {
            get
            {
                return ResourceManager.GetString("CommitteeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إضافه فرع.
        /// </summary>
        public static string CreateBranch
        {
            get
            {
                return ResourceManager.GetString("CreateBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مدخل بيانات.
        /// </summary>
        public static string DataEntry
        {
            get
            {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تأكيد الحذف.
        /// </summary>
        public static string Deleted
        {
            get
            {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عناوين تسليم العروض.
        /// </summary>
        public static string DeliverOfferAddress
        {
            get
            {
                return ResourceManager.GetString("DeliverOfferAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عناوين استالم كراسة الشروط والمواصفات يدويا.
        /// </summary>
        public static string DeliverSpecificationBookOfferAddress
        {
            get
            {
                return ResourceManager.GetString("DeliverSpecificationBookOfferAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تحرير.
        /// </summary>
        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تحرير الفرع.
        /// </summary>
        public static string EditBranch
        {
            get
            {
                return ResourceManager.GetString("EditBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم الفرع.
        /// </summary>
        public static string EnterBranchName
        {
            get
            {
                return ResourceManager.GetString("EnterBranchName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to القيمة التقديرية.
        /// </summary>
        public static string EstimatedValue
        {
            get
            {
                return ResourceManager.GetString("EstimatedValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string EstimatedValueFrom
        {
            get
            {
                return ResourceManager.GetString("EstimatedValueFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to القيمة التقديرية(من - إلى).
        /// </summary>
        public static string EstimatedValueFromTo
        {
            get
            {
                return ResourceManager.GetString("EstimatedValueFromTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إلى.
        /// </summary>
        public static string EstimatedValueTo
        {
            get
            {
                return ResourceManager.GetString("EstimatedValueTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مسئول اعتماد.
        /// </summary>
        public static string EtimadOfficer
        {
            get
            {
                return ResourceManager.GetString("EtimadOfficer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to فاكس.
        /// </summary>
        public static string Fax
        {
            get
            {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الفاكس 1.
        /// </summary>
        public static string Fax1
        {
            get
            {
                return ResourceManager.GetString("Fax1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الفاكس 2.
        /// </summary>
        public static string Fax2
        {
            get
            {
                return ResourceManager.GetString("Fax2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تفعيل نظام المنع القديم.
        /// </summary>
        public static string IsOldBlock
        {
            get
            {
                return ResourceManager.GetString("IsOldBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string MainAddress
        {
            get
            {
                return ResourceManager.GetString("MainAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to العنوان الرئيسي.
        /// </summary>
        public static string MainBranchAddress
        {
            get
            {
                return ResourceManager.GetString("MainBranchAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم لجنة فتح العروض.
        /// </summary>
        public static string OpenAgencyName
        {
            get
            {
                return ResourceManager.GetString("OpenAgencyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عناوين فتح العروض.
        /// </summary>
        public static string OpenOfferAddress
        {
            get
            {
                return ResourceManager.GetString("OpenOfferAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف 1.
        /// </summary>
        public static string Phone1
        {
            get
            {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف 2.
        /// </summary>
        public static string Phone2
        {
            get
            {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string Place
        {
            get
            {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string Position
        {
            get
            {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم صندوق البريد.
        /// </summary>
        public static string PostalCode
        {
            get
            {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معتمد التخطيط.
        /// </summary>
        public static string PrePlanningAuditor
        {
            get
            {
                return ResourceManager.GetString("PrePlanningAuditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مسئول التخطيط.
        /// </summary>
        public static string PrePlanningOfficer
        {
            get
            {
                return ResourceManager.GetString("PrePlanningOfficer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أخصائي مشتريات.
        /// </summary>
        public static string PurchaseSpecialist
        {
            get
            {
                return ResourceManager.GetString("PurchaseSpecialist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تحديد اساليب الشراء.
        /// </summary>
        public static string PurchaseType
        {
            get
            {
                return ResourceManager.GetString("PurchaseType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إعتماد نتائج وثائق التأهيل.
        /// </summary>
        public static string ReviewCheckingData
        {
            get
            {
                return ResourceManager.GetString("ReviewCheckingData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string RoleName
        {
            get
            {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بحث المستخدمين.
        /// </summary>
        public static string SearchUsers
        {
            get
            {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الجهة الفنية.
        /// </summary>
        public static string TechnicalAgencyName
        {
            get
            {
                return ResourceManager.GetString("TechnicalAgencyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to طريق إدخال رقم المنافسة.
        /// </summary>
        public static string TenderNumberInsertionType
        {
            get
            {
                return ResourceManager.GetString("TenderNumberInsertionType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName
        {
            get
            {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to صلاحيات المستخدمين.
        /// </summary>
        public static string UserRoles
        {
            get
            {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        public static string ZipCode
        {
            get
            {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
