//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.MandatoryListResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayInputs
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayInputs()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.MandatoryListResources.DisplayInputs", typeof(DisplayInputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة قائمة الزامية.
        /// </summary>
        public static string AddMandatoryList
        {
            get
            {
                return ResourceManager.GetString("AddMandatoryList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة قطاع جديد.
        /// </summary>
        public static string AddNewDivision
        {
            get
            {
                return ResourceManager.GetString("AddNewDivision", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اضافة منتج جديد.
        /// </summary>
        public static string AddNewProduct
        {
            get
            {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سيتم اعتماد القائمة الإلزامية.
        /// </summary>
        public static string ApprovalMsg
        {
            get
            {
                return ResourceManager.GetString("ApprovalMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم اعتماد منتجات القائمة الإلزامية بنجاح.
        /// </summary>
        public static string ApprovalSuccess
        {
            get
            {
                return ResourceManager.GetString("ApprovalSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معتمدة.
        /// </summary>
        public static string Approved
        {
            get
            {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم قبول طلب التعديل.
        /// </summary>
        public static string ApproveEdit
        {
            get
            {
                return ResourceManager.GetString("ApproveEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to قبول التعديل.
        /// </summary>
        public static string ApproveEditButton
        {
            get
            {
                return ResourceManager.GetString("ApproveEditButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم الالغاء.
        /// </summary>
        public static string Canceled
        {
            get
            {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم رفض الالغاء.
        /// </summary>
        public static string CancelRejected
        {
            get
            {
                return ResourceManager.GetString("CancelRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم اغلاق طلب التعديل.
        /// </summary>
        public static string ChangeRequestClosed
        {
            get
            {
                return ResourceManager.GetString("ChangeRequestClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اغلاق طلب التعديل.
        /// </summary>
        public static string CloseEdit
        {
            get
            {
                return ResourceManager.GetString("CloseEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرمز الإنشائي.
        /// </summary>
        public static string CSICode
        {
            get
            {
                return ResourceManager.GetString("CSICode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to وصف المنتج/البند (عربي).
        /// </summary>
        public static string DescriptionAr
        {
            get
            {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعريف موضح للمنتج بالمشتملات الخاصة بالمنتج والاستثناءات من المنتجات.
        /// </summary>
        public static string DescriptionArDescription
        {
            get
            {
                return ResourceManager.GetString("DescriptionArDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to وصف المنتج/البند (انجليزي).
        /// </summary>
        public static string DescriptionEn
        {
            get
            {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معلومات القطاع.
        /// </summary>
        public static string DivisionInfo
        {
            get
            {
                return ResourceManager.GetString("DivisionInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم القطاع الرئيسي.
        /// </summary>
        public static string DivisonCode
        {
            get
            {
                return ResourceManager.GetString("DivisonCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم القطاع الرئيسي (عربي).
        /// </summary>
        public static string DivisonNameAr
        {
            get
            {
                return ResourceManager.GetString("DivisonNameAr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم القطاع الرئيسي (انجليزي).
        /// </summary>
        public static string DivisonNameEn
        {
            get
            {
                return ResourceManager.GetString("DivisonNameEn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعديل منتج.
        /// </summary>
        public static string EditProduct
        {
            get
            {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ادارة منتجات القائمة الإلزامية.
        /// </summary>
        public static string ManageMandatoryList
        {
            get
            {
                return ResourceManager.GetString("ManageMandatoryList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to القائمة الإلزامية.
        /// </summary>
        public static string MandatoryList
        {
            get
            {
                return ResourceManager.GetString("MandatoryList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تفاصيل القائمة الإلزامية.
        /// </summary>
        public static string MandatoryListDetails
        {
            get
            {
                return ResourceManager.GetString("MandatoryListDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to منتجات القائمة الإلزامية.
        /// </summary>
        public static string MandatoryListProducts
        {
            get
            {
                return ResourceManager.GetString("MandatoryListProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المنتج/البند (عربي).
        /// </summary>
        public static string NameAr
        {
            get
            {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم المنتج/البند (انجليزي).
        /// </summary>
        public static string NameEn
        {
            get
            {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to السقف السعري.
        /// </summary>
        public static string PriceCelling
        {
            get
            {
                return ResourceManager.GetString("PriceCelling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المنتجات.
        /// </summary>
        public static string Products
        {
            get
            {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم الرفض.
        /// </summary>
        public static string Rejected
        {
            get
            {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم رفض طلب التعديل.
        /// </summary>
        public static string RejectEdit
        {
            get
            {
                return ResourceManager.GetString("RejectEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رفض التعديل.
        /// </summary>
        public static string RejectEditButton
        {
            get
            {
                return ResourceManager.GetString("RejectEditButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سيتم رفض القائمة الإلزامية.
        /// </summary>
        public static string RejectionMsg
        {
            get
            {
                return ResourceManager.GetString("RejectionMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم رفض منتجات القائمة الإلزامية.
        /// </summary>
        public static string RejectionSuccess
        {
            get
            {
                return ResourceManager.GetString("RejectionSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سيتم اعادة فتح القائمة الإلزامية.
        /// </summary>
        public static string ReopenMsg
        {
            get
            {
                return ResourceManager.GetString("ReopenMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم اعادة فتح القائمة الإلزامية بنجاح.
        /// </summary>
        public static string ReopenSuccess
        {
            get
            {
                return ResourceManager.GetString("ReopenSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to طلب حذف.
        /// </summary>
        public static string RequestDelete
        {
            get
            {
                return ResourceManager.GetString("RequestDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حفظ وارسال للاعتماد.
        /// </summary>
        public static string SaveAndSendToApproval
        {
            get
            {
                return ResourceManager.GetString("SaveAndSendToApproval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معلومات القطاع.
        /// </summary>
        public static string SectorInformation
        {
            get
            {
                return ResourceManager.GetString("SectorInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سيتم ارسال القائمة الالزامية إلى الاعتماد.
        /// </summary>
        public static string SendToApprovalMsg
        {
            get
            {
                return ResourceManager.GetString("SendToApprovalMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم ارسال القائمة الالزامية للإعتماد بنجاح.
        /// </summary>
        public static string SendToApprovalSuccess
        {
            get
            {
                return ResourceManager.GetString("SendToApprovalSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تحت الإنشاء.
        /// </summary>
        public static string UnderEstablishing
        {
            get
            {
                return ResourceManager.GetString("UnderEstablishing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بانتظار الاعتماد.
        /// </summary>
        public static string WaitingApproval
        {
            get
            {
                return ResourceManager.GetString("WaitingApproval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بانتظار اعتماد الالغاء.
        /// </summary>
        public static string WaitingCancelApproval
        {
            get
            {
                return ResourceManager.GetString("WaitingCancelApproval", resourceCulture);
            }
        }
    }
}
