INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (1, NULL, N'تاروت')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (2, NULL, N'الجعيمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (3, NULL, N'شدقم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (4, NULL, N'عنك')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (5, NULL, N'راس الزور')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (6, NULL, N'ام الساهك')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (7, NULL, N'الذيبية / الشرقية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (8, NULL, N'مليجة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (9, NULL, N'العيون')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (10, NULL, N'القرية العليا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (11, NULL, N'عين دار')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (12, NULL, N'الرفيعة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (13, NULL, N'القرين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (14, NULL, N'العوامية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (15, NULL, N'الشقيق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (16, NULL, N'سلوى')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (17, NULL, N'جوده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (18, NULL, N'البطحاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (19, NULL, N'العثمانية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (20, NULL, N'رأس تنورة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (21, NULL, N'القيصومة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (22, NULL, N'الخبر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (23, NULL, N'حرض')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (24, NULL, N'خريص')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (25, NULL, N'القطيف')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (26, NULL, N'رحيمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (27, NULL, N'الخفجي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (28, NULL, N'حفر الباطن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (29, NULL, N'قرية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (30, NULL, N'النعيرية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (31, NULL, N'الجبيل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (32, NULL, N'الاحساء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (33, NULL, N'الثقبة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (34, NULL, N'الصرار')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (35, NULL, N'السعيرة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (37, NULL, N'صفوى')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (38, NULL, N'الدمام')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (39, NULL, N'ابقيق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (40, NULL, N'سيهات')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (41, NULL, N'الهفوف')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (42, NULL, N'المبرز')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (43, NULL, N'الظهران')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (44, NULL, N'الرين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (45, NULL, N'خريمان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (46, NULL, N'الصحنة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (47, NULL, N'البخرة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (48, NULL, N'اشيقر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (49, NULL, N'الجله')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (50, NULL, N'الهياثم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (51, NULL, N'العمارية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (52, NULL, N'الخنيقية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (53, NULL, N'الوصيل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (54, NULL, N'وادي نساح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (55, NULL, N'الرويضة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (56, NULL, N'الوسيع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (57, NULL, N'الفويلق/القويعية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (58, NULL, N'يبرين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (59, NULL, N'تمير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (60, NULL, N'ملهم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (61, NULL, N'حوطة سدير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (62, NULL, N'سدير التويم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (63, NULL, N'الخاصره')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (64, NULL, N'القويعية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (65, NULL, N'الدوادمي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (66, NULL, N'السليل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (67, NULL, N'عفيف')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (68, NULL, N'تبراك')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (69, NULL, N'البجادية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (70, NULL, N'العيينة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (71, NULL, N'الدرعيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (72, NULL, N'عرقه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (73, NULL, N'الخرج')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (74, NULL, N'الدلم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (75, NULL, N'وادي الدواسر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (76, NULL, N'الرياض')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (77, NULL, N'الافلاج')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (78, NULL, N'الحريق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (79, NULL, N'نفي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (80, NULL, N'ساجر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (81, NULL, N'حوطة بني تميم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (82, NULL, N'الحاير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (83, NULL, N'هيت')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (84, NULL, N'المزاحمية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (85, NULL, N'ضرماء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (86, NULL, N'شقراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (87, NULL, N'الزلفي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (88, NULL, N'مرات')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (89, NULL, N'الغاط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (90, NULL, N'المجمعه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (91, NULL, N'ثادق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (92, NULL, N'حريملاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (93, NULL, N'رماح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (94, NULL, N'بنبان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (95, NULL, N'الارطاويه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (96, NULL, N'روضة سدير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (97, NULL, N'سدوس')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (98, NULL, N'الوشم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (99, NULL, N'الحمادة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (100, NULL, N'جلاجل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (101, NULL, N'القصب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (102, NULL, N'السر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (103, NULL, N'شري / القصيم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (104, NULL, N'الذيبية / القصيم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (105, NULL, N'الخرما')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (106, NULL, N'جديدات')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (107, NULL, N'رياض الخبراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (108, NULL, N'البدائع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (109, NULL, N'خب الحلوة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (110, NULL, N'ابانات')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (111, NULL, N'النبهانية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (112, NULL, N'القصيعة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (113, NULL, N'خب الثنيان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (114, NULL, N'الغماس')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (115, NULL, N'المليداء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (116, NULL, N'البطين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (117, NULL, N'خضيراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (118, NULL, N'بريدة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (119, NULL, N'خب القبر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (120, NULL, N'روضة قردان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (121, NULL, N'البكيرية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (122, NULL, N'الاسياح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (123, NULL, N'عيون الجوا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (124, NULL, N'الرس')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (125, NULL, N'المذنب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (126, NULL, N'القوارة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (127, NULL, N'عقلة الصقور')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (128, NULL, N'عنيزة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (129, NULL, N'ضرية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (130, NULL, N'الشماسية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (131, NULL, N'الهدية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (132, NULL, N'رواق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (133, NULL, N'اللسيب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (134, NULL, N'خب حويلان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (135, NULL, N'خب البريدي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (136, NULL, N'المريشدية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (137, NULL, N'الدعيسة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (138, NULL, N'خب روضان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (139, NULL, N'البصر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (140, NULL, N'العريمضي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (141, NULL, N'قبة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (142, NULL, N'الشيحية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (143, NULL, N'الخبراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (144, NULL, N'الشقة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (145, NULL, N'الشعيبة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (146, NULL, N'بحرة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (147, NULL, N'عسفان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (148, NULL, N'الجرد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (149, NULL, N'ذهبان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (150, NULL, N'العرضية الجنوبية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (151, NULL, N'الحوية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (153, NULL, N'الجموم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (154, NULL, N'الخرمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (155, NULL, N'الزيمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (156, NULL, N'نمرة القوز')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (157, NULL, N'الليث')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (158, NULL, N'جدة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (159, NULL, N'الضبية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (160, NULL, N'الكامل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (161, NULL, N'ظلم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (162, NULL, N'الموية الجديد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (163, NULL, N'تربة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (164, NULL, N'الطائف')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (165, NULL, N'المحاني')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (166, NULL, N'المضيق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (167, NULL, N'الشرائع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (168, NULL, N'وادي فاطمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (169, NULL, N'مدركة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (170, NULL, N'خليص')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (171, NULL, N'رابغ')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (172, NULL, N'مكة المكرمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (173, NULL, N'القنفذة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (174, NULL, N'البرك')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (175, NULL, N'رنية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (176, NULL, N'عتود')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (177, NULL, N'مسلية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (178, NULL, N'منجد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (179, NULL, N'هروب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (180, NULL, N'الحقو')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (181, NULL, N'العالية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (182, NULL, N'الخلاوية والنجوع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (183, NULL, N'القصبة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (184, NULL, N'الحشر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (185, NULL, N'الربوعة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (186, NULL, N'أل زيدان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (187, NULL, N'بني مالك')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (188, NULL, N'فيفا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (189, NULL, N'بلغازي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (190, NULL, N'الكدمي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (191, NULL, N'صبياء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (192, NULL, N'السلب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (193, NULL, N'بيش')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (194, NULL, N'احد المسارحه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (195, NULL, N'جازان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (196, NULL, N'الخوبة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (197, NULL, N'الشقيق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (198, NULL, N'صامطه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (199, NULL, N'الريث')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (200, NULL, N'بني قيس')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (201, NULL, N'الحميراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (202, NULL, N'فرسان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (203, NULL, N'القوز الجعافرة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (204, NULL, N'السهي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (205, NULL, N'المضايا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (206, NULL, N'وادي جيزان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (207, NULL, N'ضمد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (208, NULL, N'الشقيري')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (209, NULL, N'ابوعريش')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (210, NULL, N'القحمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (211, NULL, N'العارضة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (212, NULL, N'القفل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (213, NULL, N'الطوال')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (214, NULL, N'الموسم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (215, NULL, N'الدرب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (216, NULL, N'بني عدوان وبني حرير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (217, NULL, N'يبس')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (218, NULL, N'زناد البطاط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (219, NULL, N'الجوه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (220, NULL, N'المخواه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (221, NULL, N'شدا الاسفل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (222, NULL, N'شدا الاعلي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (223, NULL, N'كرا الحائط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (224, NULL, N'بيضان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (225, NULL, N'الباحه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (226, NULL, N'الحجره')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (227, NULL, N'الشواء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (228, NULL, N'قلوه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (229, NULL, N'نيرا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (230, NULL, N'ناوان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (231, NULL, N'معشوقه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (232, NULL, N'بيده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (233, NULL, N'بلخزمر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (234, NULL, N'دوس')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (235, NULL, N'برحرح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (236, NULL, N'الفرعه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (237, NULL, N'بني ظبيان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (238, NULL, N'القري')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (239, NULL, N'بلجرشي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (240, NULL, N'بني كبير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (241, NULL, N'بالشهم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (242, NULL, N'نخال')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (243, NULL, N'العقيق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (244, NULL, N'غامد الزناد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (245, NULL, N'جرب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (246, NULL, N'بني حسن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (247, NULL, N'باللسود')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (248, NULL, N'تربة الخياله')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (249, NULL, N'المندق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (250, NULL, N'بادية بني كبير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (251, NULL, N'المياه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (252, NULL, N'السليمي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (253, NULL, N'الروضه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (254, NULL, N'موقق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (255, NULL, N'الزبيره')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (256, NULL, N'تربه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (257, NULL, N'الاجفر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (258, NULL, N'الخوير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (259, NULL, N'المعرش')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (260, NULL, N'مرغان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (261, NULL, N'العيثمه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (262, NULL, N'الرقب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (263, NULL, N'قاع حجلا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (264, NULL, N'النحيثيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (265, NULL, N'البعايث')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (266, NULL, N'النيصيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (267, NULL, N'حائل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (268, NULL, N'المستجده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (269, NULL, N'ريع البكر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (270, NULL, N'الغزاله')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (271, NULL, N'سقف')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (272, NULL, N'الهويدي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (273, NULL, N'عقلة بن جبرين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (274, NULL, N'غمره')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (275, NULL, N'العظيم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (276, NULL, N'سميراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (277, NULL, N'عقلة بن طواله')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (278, NULL, N'المقبيح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (279, NULL, N'عقلة بن داني')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (280, NULL, N'فيد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (281, NULL, N'الساقيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (282, NULL, N'طابه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (283, NULL, N'الجحفه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (284, NULL, N'الشنان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (285, NULL, N'العدوه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (286, NULL, N'رك')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (287, NULL, N'النص')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (288, NULL, N'السبعان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (289, NULL, N'قصر العشروات')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (290, NULL, N'الوادي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (291, NULL, N'قفار')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (292, NULL, N'عقده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (293, NULL, N'الحفير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (294, NULL, N'الغويد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (295, NULL, N'بيضاء نثيل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (296, NULL, N'عمائر بن صنعاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (297, NULL, N'الشملي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (298, NULL, N'ضرغط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (299, NULL, N'انبوان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (300, NULL, N'الحائط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (301, NULL, N'المرير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (302, NULL, N'صفيط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (303, NULL, N'الدابيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (304, NULL, N'خفيج ام هشيم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (305, NULL, N'روض بن هادي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (306, NULL, N'الشيحيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (307, NULL, N'قنا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (308, NULL, N'جبه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (309, NULL, N'ضبيعيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (310, NULL, N'بقعاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (311, NULL, N'ام القليان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (312, NULL, N'السعيره')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (313, NULL, N'الخطه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (314, NULL, N'الشقيق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (315, NULL, N'الكهفه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (316, NULL, N'الحليفة السفلي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (317, NULL, N'الثماميه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (318, NULL, N'وسيطاء الحفن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (319, NULL, N'بجده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (320, NULL, N'حالة عمار')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (321, NULL, N'الفوهة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (322, NULL, N'شقري')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (323, NULL, N'رحيب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (324, NULL, N'البديعه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (325, NULL, N'فجر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (326, NULL, N'الاخضر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (327, NULL, N'الجبعاويه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (328, NULL, N'تيماء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (329, NULL, N'القليبه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (330, NULL, N'الشايب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (331, NULL, N'الطلعه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (332, NULL, N'تبوك')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (333, NULL, N'الزيته')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (334, NULL, N'ضباء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (335, NULL, N'الوجه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (336, NULL, N'املج')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (337, NULL, N'البدع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (338, NULL, N'جديدة عرعر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (339, NULL, N'رفحاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (340, NULL, N'الشعبه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (341, NULL, N'الجراني')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (342, NULL, N'حزم الجلامن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (343, NULL, N'سماح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (344, NULL, N'ساموده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (345, NULL, N'نصاب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (346, NULL, N'ام رضمه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (347, NULL, N'لينه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (348, NULL, N'طريف')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (349, NULL, N'الصحن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (350, NULL, N'الدويد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (351, NULL, N'عرعر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (352, NULL, N'لوقه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (353, NULL, N'العويقيله')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (354, NULL, N'ابو عجرم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (355, NULL, N'ثنية ام نخيله')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (356, NULL, N'ميقوع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (357, NULL, N'النبك ابوقصر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (359, NULL, N'صفان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (360, NULL, N'الاضارع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (361, NULL, N'اللقائط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (362, NULL, N'قارا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (363, NULL, N'دومة الجندل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (364, NULL, N'عذفاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (365, NULL, N'خوعاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (366, NULL, N'الطبري')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (367, NULL, N'صوير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (368, NULL, N'الشويحطيه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (369, NULL, N'زلوم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (370, NULL, N'المرير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (371, NULL, N'العيساوية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (372, NULL, N'بسيطاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (373, NULL, N'الحديثة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (374, NULL, N'مركز الوادي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (375, NULL, N'عين الحواس')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (376, NULL, N'القريات')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (377, NULL, N'عسيله')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (378, NULL, N'موارد الهوج')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (379, NULL, N'فعيراء الطبيق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (380, NULL, N'سكاكا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (381, NULL, N'طبرجل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (382, NULL, N'الشقيقه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (383, NULL, N'الطوير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (384, NULL, N'حلقة عمار')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (385, NULL, N'الناصفة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (386, NULL, N'مركز الحماد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (387, NULL, N'رجال المع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (388, NULL, N'تهامة باللسمر وباللحمر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (389, NULL, N'المجارده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (390, NULL, N'ثربان')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (391, NULL, N'بارق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (392, NULL, N'بحر ابو سكينه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (393, NULL, N'يعري')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (394, NULL, N'المضه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (395, NULL, N'العين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (396, NULL, N'طريب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (397, NULL, N'العرين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (398, NULL, N'الامواه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (399, NULL, N'ظهران الجنوب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (400, NULL, N'الحرجه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (401, NULL, N'الحبيل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (402, NULL, N'البشائر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (403, NULL, N'خثعم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (404, NULL, N'بلقرن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (405, NULL, N'ال سلمه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (406, NULL, N'السرح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (407, NULL, N'النماص')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (408, NULL, N'تنومه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (409, NULL, N'الفيض')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (410, NULL, N'الفرشه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (411, NULL, N'الجوه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (412, NULL, N'العرقين')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (413, NULL, N'احد رفيده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (414, NULL, N'خميس مشيط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (415, NULL, N'سلطان حجلا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (416, NULL, N'شري')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (417, NULL, N'شعف شهران')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (418, NULL, N'ابها')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (419, NULL, N'باللحمر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (420, NULL, N'طبب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (421, NULL, N'خيبر الجنوب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (422, NULL, N'الحمضه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (423, NULL, N'تثليث')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (424, NULL, N'قنا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (425, NULL, N'جمعة ربيعه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (426, NULL, N'حيد عبش')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (427, NULL, N'سبت العلايا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (428, NULL, N'وادي تندحة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (429, NULL, N'البرك/عسير')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (430, NULL, N'باشوت')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (431, NULL, N'بني عمرو')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (432, NULL, N'وادي الحياه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (433, NULL, N'سراة عبيده')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (434, NULL, N'عفراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (435, NULL, N'باللسمر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (436, NULL, N'بيشه')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (437, NULL, N'ابن هشبل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (438, NULL, N'ثلوث المنظر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (439, NULL, N'محايل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (440, NULL, N'المجمع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (441, NULL, N'حبونا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (442, NULL, N'بدر الجنوب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (443, NULL, N'الصفاح')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (444, NULL, N'قطن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (445, NULL, N'ثار')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (446, NULL, N'هويمل')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (447, NULL, N'ابوشداد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (448, NULL, N'شقة الكناور')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (449, NULL, N'خباش')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (450, NULL, N'الخرعاء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (451, NULL, N'الخضراء')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (452, NULL, N'الحصينية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (453, NULL, N'العريسة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (454, NULL, N'رجلا الشمالية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (455, NULL, N'ابو ثامر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (456, NULL, N'الجربة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (457, NULL, N'الحضن')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (458, NULL, N'الموفجة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (459, NULL, N'شعب بران')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (460, NULL, N'حمى')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (461, NULL, N'الخالدة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (462, NULL, N'ثجر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (463, NULL, N'نجران')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (464, NULL, N'هدادة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (465, NULL, N'بئر عسكر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (466, NULL, N'الجلدة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (467, NULL, N'ام الوهط')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (468, NULL, N'المنخلي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (469, NULL, N'قلمة خجيم')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (470, NULL, N'تمامي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (471, NULL, N'الوديعة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (472, NULL, N'شرورة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (473, NULL, N'الحرشف')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (474, NULL, N'عاكفة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (475, NULL, N'يدمة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (476, NULL, N'الخانق')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (477, NULL, N'مهد الذهب')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (478, NULL, N'الفريش')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (479, NULL, N'ابيار الماشبي')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (480, NULL, N'المهد')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (481, NULL, N'المدينة المنورة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (482, NULL, N'ينبع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (483, NULL, N'بدر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (484, NULL, N'الحسو')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (485, NULL, N'الحناكية')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (486, NULL, N'الصويدرة')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (487, NULL, N'وادي الفرع')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (488, NULL, N'العلا')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (489, NULL, N'خيبر')
INSERT [Lookups].[City] ([CityID], [NameEnglish], [NameArabic]) VALUES (490, NULL, N'المليليح')
GO