 INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (1, N'AW:آروبا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (2, N'AZ:أذربيجان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (3, N'AM:أرمينيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (4, N'ES:أسبانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (5, N'AU:أستراليا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (6, N'AF:أفغانستان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (7, N'AL:ألبانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (8, N'DE:ألمانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (9, N'AG:أنتيجوا وبربودا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (10, N'AO:أنجولا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (11, N'AI:أنجويلا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (12, N'AD:أندورا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (13, N'UY:أورجواي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (14, N'UZ:أوزبكستان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (15, N'UG:أوغندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (16, N'UA:أوكرانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (17, N'IE:أيرلندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (18, N'IS:أيسلندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (19, N'ET:اثيوبيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (20, N'ER:اريتريا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (21, N'EE:استونيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (22, N'PN:فلسطين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (23, N'AR:الأرجنتين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (24, N'JO:الأردن')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (25, N'EC:الاكوادور')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (26, N'AE:الامارات العربية المتحدة')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (27, N'BS:الباهاما')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (28, N'BH:البحرين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (29, N'BR:البرازيل')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (30, N'PT:البرتغال')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (31, N'BA:البوسنة والهرسك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (32, N'GA:الجابون')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (33, N'ME:الجبل الأسود')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (34, N'DZ:الجزائر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (35, N'DK:الدانمرك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (36, N'CV:الرأس الأخضر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (37, N'SV:السلفادور')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (38, N'SN:السنغال')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (39, N'SD:السودان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (40, N'SE:السويد')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (41, N'EH:الصحراء الغربية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (42, N'SO:الصومال')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (43, N'CN:الصين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (44, N'IQ:العراق')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (45, N'VA:الفاتيكان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (46, N'PH:الفيلبين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (47, N'AQ:القطب الجنوبي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (48, N'CM:الكاميرون')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (49, N'CG:الكونغو - برازافيل')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (50, N'KW:الكويت')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (51, N'HU:المجر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (52, N'IO:المحيط الهندي البريطاني')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (53, N'MA:المغرب')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (54, N'TF:المقاطعات الجنوبية الفرنسية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (55, N'MX:المكسيك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (56, N'SA:المملكة العربية السعودية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (57, N'GB:المملكة المتحدة')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (58, N'NO:النرويج')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (59, N'AT:النمسا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (60, N'NE:النيجر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (61, N'IN:الهند')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (62, N'US:الولايات المتحدة الأمريكية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (63, N'JP:اليابان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (64, N'YE:اليمن')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (65, N'GR:اليونان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (66, N'ID:اندونيسيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (67, N'IR:ايران')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (68, N'IT:ايطاليا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (69, N'PG:بابوا غينيا الجديدة')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (70, N'PY:باراجواي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (71, N'PK:باكستان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (72, N'PW:بالاو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (73, N'BW:بتسوانا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (74, N'PN:بتكايرن')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (75, N'BB:بربادوس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (76, N'BM:برمودا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (77, N'BN:بروناي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (78, N'BE:بلجيكا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (79, N'BG:بلغاريا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (80, N'BZ:بليز')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (81, N'BD:بنجلاديش')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (82, N'PA:بنما')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (83, N'BJ:بنين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (84, N'BT:بوتان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (85, N'PR:بورتوريكو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (86, N'BF:بوركينا فاسو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (87, N'BI:بوروندي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (88, N'PL:بولندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (89, N'BO:بوليفيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (90, N'PF:بولينيزيا الفرنسية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (91, N'PE:بيرو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (92, N'TZ:تانزانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (93, N'TH:تايلند')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (94, N'TW:تايوان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (95, N'TM:تركمانستان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (96, N'TR:تركيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (97, N'TT:ترينيداد وتوباغو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (98, N'TD:تشاد')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (99, N'TG:توجو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (100, N'TV:توفالو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (101, N'TK:توكيلو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (102, N'TO:تونجا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (103, N'TN:تونس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (104, N'TL:تيمور الشرقية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (105, N'JM:جامايكا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (106, N'GI:جبل طارق')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (107, N'GD:جرينادا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (108, N'GL:جرينلاند')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (109, N'AX:جزر أولان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (110, N'AN:جزر الأنتيل الهولندية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (111, N'TC:جزر الترك وجايكوس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (112, N'KM:جزر القمر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (113, N'KY:جزر الكايمن')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (114, N'MH:جزر المارشال')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (115, N'MV:جزر الملديف')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (116, N'UM:جزر الولايات المتحدة البعيدة الصغيرة')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (117, N'SB:جزر سليمان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (118, N'FO:جزر فارو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (119, N'VI:جزر فرجين الأمريكية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (120, N'VG:جزر فرجين البريطانية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (121, N'FK:جزر فوكلاند')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (122, N'CK:جزر كوك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (123, N'CC:جزر كوكوس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (124, N'MP:جزر ماريانا الشمالية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (125, N'WF:جزر والس وفوتونا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (126, N'CX:جزيرة الكريسماس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (127, N'BV:جزيرة بوفيه')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (128, N'IM:جزيرة مان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (129, N'NF:جزيرة نورفوك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (130, N'HM:جزيرة هيرد وماكدونالد')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (131, N'CF:جمهورية افريقيا الوسطى')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (132, N'CZ:جمهورية التشيك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (133, N'DO:جمهورية الدومينيك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (134, N'CD:جمهورية الكونغو الديمقراطية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (135, N'ZA:جمهورية جنوب افريقيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (136, N'GT:جواتيمالا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (137, N'GP:جوادلوب')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (138, N'GU:جوام')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (139, N'GE:جورجيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (140, N'GS:جورجيا الجنوبية وجزر ساندويتش الجنوبية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (141, N'DJ:جيبوتي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (142, N'JE:جيرسي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (143, N'DM:دومينيكا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (144, N'RW:رواندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (145, N'RU:روسيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (146, N'BY:روسيا البيضاء')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (147, N'RO:رومانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (148, N'RE:روينيون')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (149, N'ZM:زامبيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (150, N'ZW:زيمبابوي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (151, N'CI:ساحل العاج')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (152, N'WS:ساموا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (153, N'AS:ساموا الأمريكية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (154, N'SM:سان مارينو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (155, N'PM:سانت بيير وميكولون')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (156, N'VC:سانت فنسنت وغرنادين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (157, N'KN:سانت كيتس ونيفيس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (158, N'LC:سانت لوسيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (159, N'MF:سانت مارتين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (160, N'SH:سانت هيلنا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (161, N'ST:ساو تومي وبرينسيبي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (162, N'LK:سريلانكا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (163, N'SJ:سفالبارد وجان مايان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (164, N'SK:سلوفاكيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (165, N'SI:سلوفينيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (166, N'SG:سنغافورة')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (167, N'SZ:سوازيلاند')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (168, N'SY:سوريا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (169, N'SR:سورينام')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (170, N'CH:سويسرا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (171, N'SL:سيراليون')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (172, N'SC:سيشل')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (173, N'CL:شيلي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (174, N'RS:صربيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (175, N'CS:صربيا والجبل الأسود')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (176, N'TJ:طاجكستان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (177, N'OM:عمان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (178, N'GM:غامبيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (179, N'GH:غانا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (180, N'GF:غويانا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (181, N'GY:غيانا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (182, N'GN:غينيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (183, N'GQ:غينيا الاستوائية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (184, N'GW:غينيا بيساو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (185, N'VU:فانواتو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (186, N'FR:فرنسا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (187, N'PS:فلسطين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (188, N'VE:فنزويلا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (189, N'FI:فنلندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (190, N'VN:فيتنام')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (191, N'FJ:فيجي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (192, N'CY:قبرص')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (193, N'KG:قرغيزستان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (194, N'QA:قطر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (195, N'KZ:كازاخستان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (196, N'NC:كاليدونيا الجديدة')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (197, N'HR:كرواتيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (198, N'KH:كمبوديا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (199, N'CA:كندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (200, N'CU:كوبا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (201, N'KR:كوريا الجنوبية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (202, N'KP:كوريا الشمالية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (203, N'CR:كوستاريكا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (204, N'CO:كولومبيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (205, N'KI:كيريباتي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (206, N'KE:كينيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (207, N'LV:لاتفيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (208, N'LA:لاوس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (209, N'LB:لبنان')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (210, N'LU:لوكسمبورج')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (211, N'LY:ليبيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (212, N'LR:ليبيريا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (213, N'LT:ليتوانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (214, N'LI:ليختنشتاين')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (215, N'LS:ليسوتو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (216, N'MQ:مارتينيك')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (217, N'MO:ماكاو الصينية')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (218, N'MT:مالطا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (219, N'ML:مالي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (220, N'MY:ماليزيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (221, N'YT:مايوت')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (222, N'MG:مدغشقر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (223, N'EG:مصر')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (224, N'MK:مقدونيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (225, N'MW:ملاوي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (226, N'ZZ:منطقة غير معرفة')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (227, N'MN:منغوليا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (228, N'MR:موريتانيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (229, N'MU:موريشيوس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (230, N'MZ:موزمبيق')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (231, N'MD:مولدافيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (232, N'MC:موناكو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (233, N'MS:مونتسرات')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (234, N'MM:ميانمار')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (235, N'FM:ميكرونيزيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (236, N'NA:ناميبيا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (237, N'NR:نورو')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (238, N'NP:نيبال')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (239, N'NG:نيجيريا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (240, N'NI:نيكاراجوا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (241, N'NZ:نيوزيلاندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (242, N'NU:نيوي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (243, N'HT:هايتي')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (244, N'HN:هندوراس')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (245, N'NL:هولندا')
INSERT [LookUps].[Country] ([CountryId], [NameAr]) VALUES (246, N'HK:هونج كونج الصينية')