//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.PrePlanningResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayInputs
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayInputs()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.PrePlanningResources.DisplayInputs", typeof(DisplayInputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كود الجهة.
        /// </summary>
        public static string AgencyCode
        {
            get
            {
                return ResourceManager.GetString("AgencyCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إسم الجهة.
        /// </summary>
        public static string AgencyName
        {
            get
            {
                return ResourceManager.GetString("AgencyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أيام.
        /// </summary>
        public static string Days
        {
            get
            {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مده التنفيذ المتوقعه.
        /// </summary>
        public static string Duration
        {
            get
            {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to أيام.
        /// </summary>
        public static string DurationInDays
        {
            get
            {
                return ResourceManager.GetString("DurationInDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شهور.
        /// </summary>
        public static string DurationInMonths
        {
            get
            {
                return ResourceManager.GetString("DurationInMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سنين.
        /// </summary>
        public static string DurationInYears
        {
            get
            {
                return ResourceManager.GetString("DurationInYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التنفيذ.
        /// </summary>
        public static string Execution
        {
            get
            {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مدة التنفيذ.
        /// </summary>
        public static string ExecutionPeriod
        {
            get
            {
                return ResourceManager.GetString("ExecutionPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مكان التنفيذ.
        /// </summary>
        public static string ExecutionPlace
        {
            get
            {
                return ResourceManager.GetString("ExecutionPlace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم التسلسل.
        /// </summary>
        public static string IndexNumber
        {
            get
            {
                return ResourceManager.GetString("IndexNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شهور.
        /// </summary>
        public static string Months
        {
            get
            {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التخطيط المسبق.
        /// </summary>
        public static string PrePlanning
        {
            get
            {
                return ResourceManager.GetString("PrePlanning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إضافة\تعديل تخطيط مسبق.
        /// </summary>
        public static string PrePlanningManagement
        {
            get
            {
                return ResourceManager.GetString("PrePlanningManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تفاصيل التخطيط المسبق.
        /// </summary>
        public static string PrePrePlanningDetails
        {
            get
            {
                return ResourceManager.GetString("PrePrePlanningDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to وصف المشروع.
        /// </summary>
        public static string ProjectDescription
        {
            get
            {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إسم المشروع.
        /// </summary>
        public static string ProjectName
        {
            get
            {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to طبيعة المشروع.
        /// </summary>
        public static string ProjectNature
        {
            get
            {
                return ResourceManager.GetString("ProjectNature", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نوع المشروع.
        /// </summary>
        public static string ProjectType
        {
            get
            {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سبب الرفض.
        /// </summary>
        public static string RejectionReason
        {
            get
            {
                return ResourceManager.GetString("RejectionReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الربع السنوي.
        /// </summary>
        public static string YearQuarter
        {
            get
            {
                return ResourceManager.GetString("YearQuarter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سنين.
        /// </summary>
        public static string Years
        {
            get
            {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
