//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.BlockResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.BlockResources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ممنوع بالفعل.
        /// </summary>
        public static string AlreadyBlocked
        {
            get
            {
                return ResourceManager.GetString("AlreadyBlocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ممنوع بالفعل.
        /// </summary>
        public static string AlreadyBlocked1
        {
            get
            {
                return ResourceManager.GetString("AlreadyBlocked1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء التواصل مع مدقق البيانات.
        /// </summary>
        public static string CheckWithAuditor
        {
            get
            {
                return ResourceManager.GetString("CheckWithAuditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم اللجنة موجود من قبل.
        /// </summary>
        public static string CommitteeNameExist
        {
            get
            {
                return ResourceManager.GetString("CommitteeNameExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اللجنة غير موجودة.
        /// </summary>
        public static string CommitteeNotFound
        {
            get
            {
                return ResourceManager.GetString("CommitteeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال قيمة اكبر من الصفر.
        /// </summary>
        public static string ConditionBookNotZero
        {
            get
            {
                return ResourceManager.GetString("ConditionBookNotZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المورد غير موجود.
        /// </summary>
        public static string CrNotFound
        {
            get
            {
                return ResourceManager.GetString("CrNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المورد غير موجود.
        /// </summary>
        public static string CrNotFound1
        {
            get
            {
                return ResourceManager.GetString("CrNotFound1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مدخل البيانات فقط الذى يستطيع أن ينشئ أو يعدل المنافسة.
        /// </summary>
        public static string DataEntryPermissions
        {
            get
            {
                return ResourceManager.GetString("DataEntryPermissions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ يجب أن يكون أكبر من تاريخ اليوم.
        /// </summary>
        public static string DateLessThanToday
        {
            get
            {
                return ResourceManager.GetString("DateLessThanToday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهايه يجب ان يكون اكبر من تاريخ اليوم.
        /// </summary>
        public static string DateValidation
        {
            get
            {
                return ResourceManager.GetString("DateValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهايه يجب ان يكون اكبر من تاريخ اليوم.
        /// </summary>
        public static string DateValidation1
        {
            get
            {
                return ResourceManager.GetString("DateValidation1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الايميل موجود بالفعل.
        /// </summary>
        public static string EmailExist
        {
            get
            {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية يجب ان ]كون أكبر من تاريخ البداية.
        /// </summary>
        public static string EndDateBiggerStart
        {
            get
            {
                return ResourceManager.GetString("EndDateBiggerStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال المرفقات.
        /// </summary>
        public static string EnterAttachment
        {
            get
            {
                return ResourceManager.GetString("EnterAttachment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال المرفقات.
        /// </summary>
        public static string EnterAttachment1
        {
            get
            {
                return ResourceManager.GetString("EnterAttachment1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال نسخة من قرار المنع.
        /// </summary>
        public static string EnterAttachmentId
        {
            get
            {
                return ResourceManager.GetString("EnterAttachmentId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال سبب تقديم الطلب.
        /// </summary>
        public static string EnterBlockDetails
        {
            get
            {
                return ResourceManager.GetString("EnterBlockDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال تاريخ نهاية المنع.
        /// </summary>
        public static string EnterBlockEndDate
        {
            get
            {
                return ResourceManager.GetString("EnterBlockEndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال سبب المنع.
        /// </summary>
        public static string EnterBlockReason
        {
            get
            {
                return ResourceManager.GetString("EnterBlockReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال تاريخ بداية المنع.
        /// </summary>
        public static string EnterBlockStartDate
        {
            get
            {
                return ResourceManager.GetString("EnterBlockStartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال نوع المنع.
        /// </summary>
        public static string EnterBlockTypeId
        {
            get
            {
                return ResourceManager.GetString("EnterBlockTypeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  الرجاء إدخال نوع المنع.
        /// </summary>
        public static string EnterBlockTypeName
        {
            get
            {
                return ResourceManager.GetString("EnterBlockTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال رقم السجل التجاري.
        /// </summary>
        public static string EnterCommercialRegistrationNo
        {
            get
            {
                return ResourceManager.GetString("EnterCommercialRegistrationNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال اسم المورد التجاري.
        /// </summary>
        public static string EnterCommercialSupplierName
        {
            get
            {
                return ResourceManager.GetString("EnterCommercialSupplierName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال سعر كراسة الشروط.
        /// </summary>
        public static string EnterConditionBook
        {
            get
            {
                return ResourceManager.GetString("EnterConditionBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال عنوان استلام كراسة الشروط.
        /// </summary>
        public static string EnterConditionsBookletDeliveryAddress
        {
            get
            {
                return ResourceManager.GetString("EnterConditionsBookletDeliveryAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال التاريخ.
        /// </summary>
        public static string EnterDate
        {
            get
            {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة ايميل.
        /// </summary>
        public static string EnterEmail
        {
            get
            {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ارفاق الملف.
        /// </summary>
        public static string EnterFile
        {
            get
            {
                return ResourceManager.GetString("EnterFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال أربعين حرف علي الأقل.
        /// </summary>
        public static string EnterFourtyCharacters
        {
            get
            {
                return ResourceManager.GetString("EnterFourtyCharacters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم حذفها.
        /// </summary>
        public static string EnterIsDeleted
        {
            get
            {
                return ResourceManager.GetString("EnterIsDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال اخر موعد لاستلام الاستفسارات.
        /// </summary>
        public static string EnterLastEnqueriesDate
        {
            get
            {
                return ResourceManager.GetString("EnterLastEnqueriesDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال اخر موعد لتقديم العروض.
        /// </summary>
        public static string EnterLastOfferPresentationDate
        {
            get
            {
                return ResourceManager.GetString("EnterLastOfferPresentationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال اخر موعد لتقديم العروض.
        /// </summary>
        public static string EnterLastOfferPresentationTime
        {
            get
            {
                return ResourceManager.GetString("EnterLastOfferPresentationTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال .
        /// </summary>
        public static string EnterLicenseNumber
        {
            get
            {
                return ResourceManager.GetString("EnterLicenseNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال مكان تقديم العروض.
        /// </summary>
        public static string EnterOfferPresentationPlace
        {
            get
            {
                return ResourceManager.GetString("EnterOfferPresentationPlace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال مكان فتح العروض.
        /// </summary>
        public static string EnterOffersOpeningAddress
        {
            get
            {
                return ResourceManager.GetString("EnterOffersOpeningAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال تاريخ فتح العروض.
        /// </summary>
        public static string EnterOffersOpeningDate
        {
            get
            {
                return ResourceManager.GetString("EnterOffersOpeningDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال وقت فتح العروض.
        /// </summary>
        public static string EnterOffersOpeningTime
        {
            get
            {
                return ResourceManager.GetString("EnterOffersOpeningTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال الأساس النظامي للتشهير.
        /// </summary>
        public static string EnterOfficialBasisDefamation
        {
            get
            {
                return ResourceManager.GetString("EnterOfficialBasisDefamation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب كتابة رقم الجوال.
        /// </summary>
        public static string EnterPhone
        {
            get
            {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال البريد الإلكتروني او رقم الجوال.
        /// </summary>
        public static string EnterPhoneNumberOrEmail
        {
            get
            {
                return ResourceManager.GetString("EnterPhoneNumberOrEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال نص العقوبة.
        /// </summary>
        public static string EnterPunishment
        {
            get
            {
                return ResourceManager.GetString("EnterPunishment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال جدول كميات على الأقل.
        /// </summary>
        public static string EnterQuantitiesTable
        {
            get
            {
                return ResourceManager.GetString("EnterQuantitiesTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال عنصر واحد على الأقل فى جدول الكميات.
        /// </summary>
        public static string EnterQuantitiesTableItem
        {
            get
            {
                return ResourceManager.GetString("EnterQuantitiesTableItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال رقم القرار.
        /// </summary>
        public static string EnterResolutionNumber
        {
            get
            {
                return ResourceManager.GetString("EnterResolutionNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال عنوان تسليم العينات.
        /// </summary>
        public static string EnterSamplesAdress
        {
            get
            {
                return ResourceManager.GetString("EnterSamplesAdress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال رقم المنع.
        /// </summary>
        public static string EnterSupplierBlockId
        {
            get
            {
                return ResourceManager.GetString("EnterSupplierBlockId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار اسم الجهه الفنية.
        /// </summary>
        public static string EnterTechnicalCommittee
        {
            get
            {
                return ResourceManager.GetString("EnterTechnicalCommittee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار النشاطات.
        /// </summary>
        public static string EnterTenderActivities
        {
            get
            {
                return ResourceManager.GetString("EnterTenderActivities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار المناطق.
        /// </summary>
        public static string EnterTenderAreas
        {
            get
            {
                return ResourceManager.GetString("EnterTenderAreas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال اسم المنافسة.
        /// </summary>
        public static string EnterTenderName
        {
            get
            {
                return ResourceManager.GetString("EnterTenderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال رقم المنافسة.
        /// </summary>
        public static string EnterTenderNumber
        {
            get
            {
                return ResourceManager.GetString("EnterTenderNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال الغرض من المنافسة.
        /// </summary>
        public static string EnterTenderPurpose
        {
            get
            {
                return ResourceManager.GetString("EnterTenderPurpose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال نص المخالفة.
        /// </summary>
        public static string EnterViolation
        {
            get
            {
                return ResourceManager.GetString("EnterViolation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق خطأ الرجاء إعادة ارسال رمز التحقق.
        /// </summary>
        public static string ExpiredActivationCode
        {
            get
            {
                return ResourceManager.GetString("ExpiredActivationCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم السجل التجاري المدخل غير صحيح.
        /// </summary>
        public static string InvalidCommercialRegistrationNo
        {
            get
            {
                return ResourceManager.GetString("InvalidCommercialRegistrationNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اخر موعد لإستلام استفسارات الموردين يجب أن يكون أقل من تاريخ فتح العروض وتاريخ تقديم العروض.
        /// </summary>
        public static string InvalidLastEnqueriesDate
        {
            get
            {
                return ResourceManager.GetString("InvalidLastEnqueriesDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم غير صحيح.
        /// </summary>
        public static string InvalidNumber
        {
            get
            {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم غير صحيح.
        /// </summary>
        public static string InvalidNumber1
        {
            get
            {
                return ResourceManager.GetString("InvalidNumber1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء مراجعة البيانات والمحاولة مرة اخرى.
        /// </summary>
        public static string ModelDataError
        {
            get
            {
                return ResourceManager.GetString("ModelDataError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ يجب ألا يكون أجازة رسمية.
        /// </summary>
        public static string OfficialVacationDate
        {
            get
            {
                return ResourceManager.GetString("OfficialVacationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ المنع يجب ان يكون اكبر من تاريخ اليوم.
        /// </summary>
        public static string PermanentDateValidate
        {
            get
            {
                return ResourceManager.GetString("PermanentDateValidate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال موجود بالفعل.
        /// </summary>
        public static string PhoneExist
        {
            get
            {
                return ResourceManager.GetString("PhoneExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار نوع الكيان .
        /// </summary>
        public static string SelectOrganizationTypeId
        {
            get
            {
                return ResourceManager.GetString("SelectOrganizationTypeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار اسلوب شراء واحد على الاقل.
        /// </summary>
        public static string SelectPurchaseMethod
        {
            get
            {
                return ResourceManager.GetString("SelectPurchaseMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء اختيار نوع المورد.
        /// </summary>
        public static string SelectSupplierTypeId
        {
            get
            {
                return ResourceManager.GetString("SelectSupplierTypeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال إسم الجهة الفنية.
        /// </summary>
        public static string TechnicalOrganizationRequired
        {
            get
            {
                return ResourceManager.GetString("TechnicalOrganizationRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المنافسة غير موجودة.
        /// </summary>
        public static string TenderNotExist
        {
            get
            {
                return ResourceManager.GetString("TenderNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خطأ فى الارسال.
        /// </summary>
        public static string TenderSentFailed
        {
            get
            {
                return ResourceManager.GetString("TenderSentFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع، الرجاء المحاولة مرة اخرى.
        /// </summary>
        public static string UnexpectedError
        {
            get
            {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال رقم سجل تجاري صحيح.
        /// </summary>
        public static string ValidateCommercialRegistrationNo
        {
            get
            {
                return ResourceManager.GetString("ValidateCommercialRegistrationNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ يجب ألا يكون أجازة أسبوعية.
        /// </summary>
        public static string WeekendDate
        {
            get
            {
                return ResourceManager.GetString("WeekendDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صحيح.
        /// </summary>
        public static string WrongEmail
        {
            get
            {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
    }
}
