//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.CommunicationRequest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.CommunicationRequest.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم إعتماد طلب تمديد سريان العروض للمنافسة.
        /// </summary>
        public static string ApproveConfirmationExtendOffersRequest {
            get {
                return ResourceManager.GetString("ApproveConfirmationExtendOffersRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون الضمان يساوي نصف قيمة  الضمان الابتدائي ساري لمدة لاتقل عن ثلاثين يوما.
        /// </summary>
        public static string BankGuaranteeMSG {
            get {
                return ResourceManager.GetString("BankGuaranteeMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي إدخال التفاصيل.
        /// </summary>
        public static string EnterDetails {
            get {
                return ResourceManager.GetString("EnterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال ملاحظات الرفض لكل طلب تظلم.
        /// </summary>
        public static string EnterRejectionNotes {
            get {
                return ResourceManager.GetString("EnterRejectionNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال طلبك للجهة الحكومية وستقوم بالرد على طلبك, سيتم اشعاركم فور الرد.
        /// </summary>
        public static string ExtendOffersPresentationDatesRequestSent {
            get {
                return ResourceManager.GetString("ExtendOffersPresentationDatesRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند التأكيد سيتم ارسال طلب التمديد للاعتماد وإزالة المدخلات على العروض التي تم ترسيتها أو استبعادها.
        /// </summary>
        public static string ExtendOfferValidityAndResetAwardingActions {
            get {
                return ResourceManager.GetString("ExtendOfferValidityAndResetAwardingActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند التأكيد سيتم اعتماد طلب التمديد وإزالة المدخلات على العروض التي تم ترسيتها أو استبعادها.
        /// </summary>
        public static string ExtendOfferValidityAndResetAwardingActionsDirectPurchaseMember {
            get {
                return ResourceManager.GetString("ExtendOfferValidityAndResetAwardingActionsDirectPurchaseMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد الارسال.
        /// </summary>
        public static string NegotiationRequestForApproveModalTitle {
            get {
                return ResourceManager.GetString("NegotiationRequestForApproveModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تصعيد التطلب الى لجنة النظر بالتظلمات.
        /// </summary>
        public static string PlainTrequestEscalated {
            get {
                return ResourceManager.GetString("PlainTrequestEscalated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك إختر الإجراء المتخذ.
        /// </summary>
        public static string PleaseSelectTakenProcedure {
            get {
                return ResourceManager.GetString("PleaseSelectTakenProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال طلب الاعتماد بنجاح.
        /// </summary>
        public static string RequestSentToApprovedSuccessfully {
            get {
                return ResourceManager.GetString("RequestSentToApprovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم ارسال طلب إعتماد بدء التفاوض للمنافسة.
        /// </summary>
        public static string SendNegotiationRequestForApprove {
            get {
                return ResourceManager.GetString("SendNegotiationRequestForApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم ارسال طلب إعتماد تمديد سريان العروض للمنافسة.
        /// </summary>
        public static string SendToApproveExtendOffersRequest {
            get {
                return ResourceManager.GetString("SendToApproveExtendOffersRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عليك تسليم الضمان الابتدئي الذي تم تمديد سريانة وإلا ستعتبر منسحب ولا يعتد بالقبول المبدئي.
        /// </summary>
        public static string YouHaveToUploadInitialGuarantee {
            get {
                return ResourceManager.GetString("YouHaveToUploadInitialGuarantee", resourceCulture);
            }
        }
    }
}
