//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COCSubscriptionInquiryService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ejada.com", ConfigurationName="COCSubscriptionInquiryService.COCSubscriptionInquiry")]
    public interface COCSubscriptionInquiry
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="COCSubscriptionInquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<COCSubscriptionInquiryService.COCSubscriptionInquiryResponse> COCSubscriptionInquiryAsync(COCSubscriptionInquiryService.COCSubscriptionInquiryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class COCSubscriptionInquiryRq_Type
    {
        
        private MsgRqHdr_Type msgRqHdrField;
        
        private COCSubscriptionInquiryRqBody_Type bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRqHdr_Type MsgRqHdr
        {
            get
            {
                return this.msgRqHdrField;
            }
            set
            {
                this.msgRqHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public COCSubscriptionInquiryRqBody_Type Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MsgRqHdr_Type
    {
        
        private string rqUIDField;
        
        private string processUIDField;
        
        private string sessionIdField;
        
        private string sCIdField;
        
        private string serviceIdField;
        
        private string funcIdField;
        
        private long rqModeField;
        
        private bool rqModeFieldSpecified;
        
        private PartyId_Type partyIdField;
        
        private string userIdField;
        
        private string proxyUserIdField;
        
        private string clientDtField;
        
        private string echoDataField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProcessUID
        {
            get
            {
                return this.processUIDField;
            }
            set
            {
                this.processUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SCId
        {
            get
            {
                return this.sCIdField;
            }
            set
            {
                this.sCIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FuncId
        {
            get
            {
                return this.funcIdField;
            }
            set
            {
                this.funcIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long RqMode
        {
            get
            {
                return this.rqModeField;
            }
            set
            {
                this.rqModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RqModeSpecified
        {
            get
            {
                return this.rqModeFieldSpecified;
            }
            set
            {
                this.rqModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public PartyId_Type PartyId
        {
            get
            {
                return this.partyIdField;
            }
            set
            {
                this.partyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ProxyUserId
        {
            get
            {
                return this.proxyUserIdField;
            }
            set
            {
                this.proxyUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ClientDt
        {
            get
            {
                return this.clientDtField;
            }
            set
            {
                this.clientDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class PartyId_Type
    {
        
        private string partyIdNumField;
        
        private PartyIdType_Type partyIdTypeField;
        
        private bool partyIdTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartyIdNum
        {
            get
            {
                return this.partyIdNumField;
            }
            set
            {
                this.partyIdNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PartyIdType_Type PartyIdType
        {
            get
            {
                return this.partyIdTypeField;
            }
            set
            {
                this.partyIdTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartyIdTypeSpecified
        {
            get
            {
                return this.partyIdTypeFieldSpecified;
            }
            set
            {
                this.partyIdTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public enum PartyIdType_Type
    {
        
        /// <remarks/>
        IqamaNumber,
        
        /// <remarks/>
        NationalId,
        
        /// <remarks/>
        CommercialRegistration,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("700Code")]
        Item700Code,
        
        /// <remarks/>
        AccountNumber,
        
        /// <remarks/>
        FamilyCardNumber,
        
        /// <remarks/>
        BorderNumber,
        
        /// <remarks/>
        PassportNumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MembershipCapital_Type
    {
        
        private string announcedCapitalField;
        
        private string paidCapitalField;
        
        private string rateOfNationalCapitalField;
        
        private string rateOfForeignCapitalField;
        
        private string allowedSharesField;
        
        private string paidSharesField;
        
        private string numberOfSaudisMaleField;
        
        private string numberOfSaudisFemaleField;
        
        private string numberOfNonSaudisMaleField;
        
        private string numberOfNonSaudisFemaleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AnnouncedCapital
        {
            get
            {
                return this.announcedCapitalField;
            }
            set
            {
                this.announcedCapitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PaidCapital
        {
            get
            {
                return this.paidCapitalField;
            }
            set
            {
                this.paidCapitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RateOfNationalCapital
        {
            get
            {
                return this.rateOfNationalCapitalField;
            }
            set
            {
                this.rateOfNationalCapitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RateOfForeignCapital
        {
            get
            {
                return this.rateOfForeignCapitalField;
            }
            set
            {
                this.rateOfForeignCapitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string AllowedShares
        {
            get
            {
                return this.allowedSharesField;
            }
            set
            {
                this.allowedSharesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string PaidShares
        {
            get
            {
                return this.paidSharesField;
            }
            set
            {
                this.paidSharesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string NumberOfSaudisMale
        {
            get
            {
                return this.numberOfSaudisMaleField;
            }
            set
            {
                this.numberOfSaudisMaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string NumberOfSaudisFemale
        {
            get
            {
                return this.numberOfSaudisFemaleField;
            }
            set
            {
                this.numberOfSaudisFemaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=8)]
        public string NumberOfNonSaudisMale
        {
            get
            {
                return this.numberOfNonSaudisMaleField;
            }
            set
            {
                this.numberOfNonSaudisMaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=9)]
        public string NumberOfNonSaudisFemale
        {
            get
            {
                return this.numberOfNonSaudisFemaleField;
            }
            set
            {
                this.numberOfNonSaudisFemaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MembershipAddress_Type
    {
        
        private string pOBoxField;
        
        private string postalCodeField;
        
        private string streetField;
        
        private string distField;
        
        private string cityNameField;
        
        private string regionField;
        
        private string locationInfoField;
        
        private string waselInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string POBox
        {
            get
            {
                return this.pOBoxField;
            }
            set
            {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Dist
        {
            get
            {
                return this.distField;
            }
            set
            {
                this.distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CityName
        {
            get
            {
                return this.cityNameField;
            }
            set
            {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LocationInfo
        {
            get
            {
                return this.locationInfoField;
            }
            set
            {
                this.locationInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WaselInfo
        {
            get
            {
                return this.waselInfoField;
            }
            set
            {
                this.waselInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MembershipOwner_Type
    {
        
        private string ownerNameField;
        
        private string ownerPrefixField;
        
        private string ownerGenderField;
        
        private string ownerNationalityField;
        
        private string ownerPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OwnerName
        {
            get
            {
                return this.ownerNameField;
            }
            set
            {
                this.ownerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OwnerPrefix
        {
            get
            {
                return this.ownerPrefixField;
            }
            set
            {
                this.ownerPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OwnerGender
        {
            get
            {
                return this.ownerGenderField;
            }
            set
            {
                this.ownerGenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OwnerNationality
        {
            get
            {
                return this.ownerNationalityField;
            }
            set
            {
                this.ownerNationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OwnerPosition
        {
            get
            {
                return this.ownerPositionField;
            }
            set
            {
                this.ownerPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MembershipActivity_Type
    {
        
        private string mainActivityField;
        
        private string secondActivityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MainActivity
        {
            get
            {
                return this.mainActivityField;
            }
            set
            {
                this.mainActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SecondActivity
        {
            get
            {
                return this.secondActivityField;
            }
            set
            {
                this.secondActivityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MembershipSijil_Type
    {
        
        private string sijilNumField;
        
        private string sijilTypeField;
        
        private string sijilSourceField;
        
        private System.DateTime sijilFromDtField;
        
        private bool sijilFromDtFieldSpecified;
        
        private string sijilFromDtHjrField;
        
        private System.DateTime sijilToDtField;
        
        private bool sijilToDtFieldSpecified;
        
        private string sijilToDtHjrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string SijilNum
        {
            get
            {
                return this.sijilNumField;
            }
            set
            {
                this.sijilNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SijilType
        {
            get
            {
                return this.sijilTypeField;
            }
            set
            {
                this.sijilTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SijilSource
        {
            get
            {
                return this.sijilSourceField;
            }
            set
            {
                this.sijilSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime SijilFromDt
        {
            get
            {
                return this.sijilFromDtField;
            }
            set
            {
                this.sijilFromDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SijilFromDtSpecified
        {
            get
            {
                return this.sijilFromDtFieldSpecified;
            }
            set
            {
                this.sijilFromDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SijilFromDtHjr
        {
            get
            {
                return this.sijilFromDtHjrField;
            }
            set
            {
                this.sijilFromDtHjrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime SijilToDt
        {
            get
            {
                return this.sijilToDtField;
            }
            set
            {
                this.sijilToDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SijilToDtSpecified
        {
            get
            {
                return this.sijilToDtFieldSpecified;
            }
            set
            {
                this.sijilToDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SijilToDtHjr
        {
            get
            {
                return this.sijilToDtHjrField;
            }
            set
            {
                this.sijilToDtHjrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MembershipEstablishment_Type
    {
        
        private string estNameField;
        
        private string estJuridicalFormField;
        
        private string estNationalityField;
        
        private string estNumOfBranchesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EstName
        {
            get
            {
                return this.estNameField;
            }
            set
            {
                this.estNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EstJuridicalForm
        {
            get
            {
                return this.estJuridicalFormField;
            }
            set
            {
                this.estJuridicalFormField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EstNationality
        {
            get
            {
                return this.estNationalityField;
            }
            set
            {
                this.estNationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string EstNumOfBranches
        {
            get
            {
                return this.estNumOfBranchesField;
            }
            set
            {
                this.estNumOfBranchesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MembershipDetails_Type
    {
        
        private string membershipIdField;
        
        private string membershipCityField;
        
        private string membershipClassField;
        
        private System.DateTime membershipFromDtField;
        
        private bool membershipFromDtFieldSpecified;
        
        private string membershipFromDtHjrField;
        
        private System.DateTime membershipToDtField;
        
        private bool membershipToDtFieldSpecified;
        
        private string membershipToDtHjrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MembershipId
        {
            get
            {
                return this.membershipIdField;
            }
            set
            {
                this.membershipIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MembershipCity
        {
            get
            {
                return this.membershipCityField;
            }
            set
            {
                this.membershipCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MembershipClass
        {
            get
            {
                return this.membershipClassField;
            }
            set
            {
                this.membershipClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime MembershipFromDt
        {
            get
            {
                return this.membershipFromDtField;
            }
            set
            {
                this.membershipFromDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MembershipFromDtSpecified
        {
            get
            {
                return this.membershipFromDtFieldSpecified;
            }
            set
            {
                this.membershipFromDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MembershipFromDtHjr
        {
            get
            {
                return this.membershipFromDtHjrField;
            }
            set
            {
                this.membershipFromDtHjrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime MembershipToDt
        {
            get
            {
                return this.membershipToDtField;
            }
            set
            {
                this.membershipToDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MembershipToDtSpecified
        {
            get
            {
                return this.membershipToDtFieldSpecified;
            }
            set
            {
                this.membershipToDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MembershipToDtHjr
        {
            get
            {
                return this.membershipToDtHjrField;
            }
            set
            {
                this.membershipToDtHjrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class COCSubscriptionInquiryRsBody_Type
    {
        
        private MembershipDetails_Type membershipDetailsField;
        
        private MembershipEstablishment_Type membershipEstablishmentField;
        
        private MembershipSijil_Type membershipSijilField;
        
        private MembershipActivity_Type membershipActivityField;
        
        private MembershipOwner_Type membershipOwnerField;
        
        private MembershipAddress_Type membershipAddressField;
        
        private string[] membershipPhoneField;
        
        private string[] membershipFaxField;
        
        private string[] membershipMobileField;
        
        private string[] membershipEmailField;
        
        private string[] membershipWebsiteField;
        
        private MembershipCapital_Type membershipCapitalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MembershipDetails_Type MembershipDetails
        {
            get
            {
                return this.membershipDetailsField;
            }
            set
            {
                this.membershipDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MembershipEstablishment_Type MembershipEstablishment
        {
            get
            {
                return this.membershipEstablishmentField;
            }
            set
            {
                this.membershipEstablishmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MembershipSijil_Type MembershipSijil
        {
            get
            {
                return this.membershipSijilField;
            }
            set
            {
                this.membershipSijilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MembershipActivity_Type MembershipActivity
        {
            get
            {
                return this.membershipActivityField;
            }
            set
            {
                this.membershipActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MembershipOwner_Type MembershipOwner
        {
            get
            {
                return this.membershipOwnerField;
            }
            set
            {
                this.membershipOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public MembershipAddress_Type MembershipAddress
        {
            get
            {
                return this.membershipAddressField;
            }
            set
            {
                this.membershipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PhoneNum", IsNullable=false)]
        public string[] MembershipPhone
        {
            get
            {
                return this.membershipPhoneField;
            }
            set
            {
                this.membershipPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FaxNum", IsNullable=false)]
        public string[] MembershipFax
        {
            get
            {
                return this.membershipFaxField;
            }
            set
            {
                this.membershipFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MobileNum", IsNullable=false)]
        public string[] MembershipMobile
        {
            get
            {
                return this.membershipMobileField;
            }
            set
            {
                this.membershipMobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Email", IsNullable=false)]
        public string[] MembershipEmail
        {
            get
            {
                return this.membershipEmailField;
            }
            set
            {
                this.membershipEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HomePageURL", IsNullable=false)]
        public string[] MembershipWebsite
        {
            get
            {
                return this.membershipWebsiteField;
            }
            set
            {
                this.membershipWebsiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public MembershipCapital_Type MembershipCapital
        {
            get
            {
                return this.membershipCapitalField;
            }
            set
            {
                this.membershipCapitalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class ResponseStatus_Type
    {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDesc
        {
            get
            {
                return this.statusDescField;
            }
            set
            {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class OverrideStatus_Type
    {
        
        private string codeField;
        
        private string descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class MsgRsHdr_Type
    {
        
        private string rqUIDField;
        
        private string processUIDField;
        
        private string sessionIdField;
        
        private string sPRefNumField;
        
        private string msgRecDtField;
        
        private OverrideStatus_Type overrideStatusField;
        
        private ResponseStatus_Type responseStatusField;
        
        private string echoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RqUID
        {
            get
            {
                return this.rqUIDField;
            }
            set
            {
                this.rqUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProcessUID
        {
            get
            {
                return this.processUIDField;
            }
            set
            {
                this.processUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SPRefNum
        {
            get
            {
                return this.sPRefNumField;
            }
            set
            {
                this.sPRefNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MsgRecDt
        {
            get
            {
                return this.msgRecDtField;
            }
            set
            {
                this.msgRecDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public OverrideStatus_Type OverrideStatus
        {
            get
            {
                return this.overrideStatusField;
            }
            set
            {
                this.overrideStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ResponseStatus_Type ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EchoData
        {
            get
            {
                return this.echoDataField;
            }
            set
            {
                this.echoDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class COCSubscriptionInquiryRs_Type
    {
        
        private MsgRsHdr_Type msgRsHdrField;
        
        private COCSubscriptionInquiryRsBody_Type bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsgRsHdr_Type MsgRsHdr
        {
            get
            {
                return this.msgRsHdrField;
            }
            set
            {
                this.msgRsHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public COCSubscriptionInquiryRsBody_Type Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ejada.com")]
    public partial class COCSubscriptionInquiryRqBody_Type
    {
        
        private string licenseNumberField;
        
        private string cityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LicenseNumber
        {
            get
            {
                return this.licenseNumberField;
            }
            set
            {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CityCode
        {
            get
            {
                return this.cityCodeField;
            }
            set
            {
                this.cityCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class COCSubscriptionInquiryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ejada.com", Order=0)]
        public COCSubscriptionInquiryService.COCSubscriptionInquiryRq_Type COCSubscriptionInquiryRq;
        
        public COCSubscriptionInquiryRequest()
        {
        }
        
        public COCSubscriptionInquiryRequest(COCSubscriptionInquiryService.COCSubscriptionInquiryRq_Type COCSubscriptionInquiryRq)
        {
            this.COCSubscriptionInquiryRq = COCSubscriptionInquiryRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class COCSubscriptionInquiryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ejada.com", Order=0)]
        public COCSubscriptionInquiryService.COCSubscriptionInquiryRs_Type COCSubscriptionInquiryRs;
        
        public COCSubscriptionInquiryResponse()
        {
        }
        
        public COCSubscriptionInquiryResponse(COCSubscriptionInquiryService.COCSubscriptionInquiryRs_Type COCSubscriptionInquiryRs)
        {
            this.COCSubscriptionInquiryRs = COCSubscriptionInquiryRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface COCSubscriptionInquiryChannel : COCSubscriptionInquiryService.COCSubscriptionInquiry, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class COCSubscriptionInquiryClient : System.ServiceModel.ClientBase<COCSubscriptionInquiryService.COCSubscriptionInquiry>, COCSubscriptionInquiryService.COCSubscriptionInquiry
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public COCSubscriptionInquiryClient(EndpointConfiguration endpointConfiguration) : 
                base(COCSubscriptionInquiryClient.GetBindingForEndpoint(endpointConfiguration), COCSubscriptionInquiryClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public COCSubscriptionInquiryClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(COCSubscriptionInquiryClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public COCSubscriptionInquiryClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(COCSubscriptionInquiryClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public COCSubscriptionInquiryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COCSubscriptionInquiryService.COCSubscriptionInquiryResponse> COCSubscriptionInquiryService.COCSubscriptionInquiry.COCSubscriptionInquiryAsync(COCSubscriptionInquiryService.COCSubscriptionInquiryRequest request)
        {
            return base.Channel.COCSubscriptionInquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<COCSubscriptionInquiryService.COCSubscriptionInquiryResponse> COCSubscriptionInquiryAsync(COCSubscriptionInquiryService.COCSubscriptionInquiryRq_Type COCSubscriptionInquiryRq)
        {
            COCSubscriptionInquiryService.COCSubscriptionInquiryRequest inValue = new COCSubscriptionInquiryService.COCSubscriptionInquiryRequest();
            inValue.COCSubscriptionInquiryRq = COCSubscriptionInquiryRq;
            return ((COCSubscriptionInquiryService.COCSubscriptionInquiry)(this)).COCSubscriptionInquiryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.COCSubscriptionInquirySOAP12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.COCSubscriptionInquirySOAP11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.COCSubscriptionInquirySOAP12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7800/COCSubscriptionInquiry");
            }
            if ((endpointConfiguration == EndpointConfiguration.COCSubscriptionInquirySOAP11))
            {
                return new System.ServiceModel.EndpointAddress("https://10.14.8.25:7909/COCSubscriptionInquiry11");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            COCSubscriptionInquirySOAP12,
            
            COCSubscriptionInquirySOAP11,
        }
    }
}
