//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOF.Etimad.Monafasat.Resources.ReportResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayInputs
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayInputs()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOF.Etimad.Monafasat.Resources.ReportResources.DisplayInputs", typeof(DisplayInputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تقرير ملف الجهة الحكومية.
        /// </summary>
        public static string AgencyFileReport
        {
            get
            {
                return ResourceManager.GetString("AgencyFileReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مقدار الوفورات.
        /// </summary>
        public static string AmountOfSavings
        {
            get
            {
                return ResourceManager.GetString("AmountOfSavings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نسبة الوفورات.
        /// </summary>
        public static string AmountOfSavingsPercentage
        {
            get
            {
                return ResourceManager.GetString("AmountOfSavingsPercentage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to متوسط المدة الزمنية لمراجعة منافسة واحدة.
        /// </summary>
        public static string AverageDurationReviewOfoneTender
        {
            get
            {
                return ResourceManager.GetString("AverageDurationReviewOfoneTender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to متوسط الانفاق للعقود.
        /// </summary>
        public static string AverageExpenditureOfContracts
        {
            get
            {
                return ResourceManager.GetString("AverageExpenditureOfContracts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معدل الانفاق.
        /// </summary>
        public static string AverageSpending
        {
            get
            {
                return ResourceManager.GetString("AverageSpending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ من.
        /// </summary>
        public static string DateFrom
        {
            get
            {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التاريخ الى .
        /// </summary>
        public static string DateTo
        {
            get
            {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الانفاق.
        /// </summary>
        public static string DetailsOfSpend
        {
            get
            {
                return ResourceManager.GetString("DetailsOfSpend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الشراء المباشير.
        /// </summary>
        public static string DirectPurchase
        {
            get
            {
                return ResourceManager.GetString("DirectPurchase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بريد الكتروني.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to وقت الانتهاء.
        /// </summary>
        public static string EndDate
        {
            get
            {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to القيمة القديريةبعد المراجعة.
        /// </summary>
        public static string EstimatedValueAfterReview
        {
            get
            {
                return ResourceManager.GetString("EstimatedValueAfterReview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to القيمة التقديرية قبل المراجعة.
        /// </summary>
        public static string EstimatedValueBeforeReview
        {
            get
            {
                return ResourceManager.GetString("EstimatedValueBeforeReview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ اول منافسة.
        /// </summary>
        public static string FirstTenderDate
        {
            get
            {
                return ResourceManager.GetString("FirstTenderDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ اخر منافسه.
        /// </summary>
        public static string LastTenderDate
        {
            get
            {
                return ResourceManager.GetString("LastTenderDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم التنبيه.
        /// </summary>
        public static string MessageName
        {
            get
            {
                return ResourceManager.GetString("MessageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تقرير حالة الإرساليات.
        /// </summary>
        public static string MessagesStatusReport
        {
            get
            {
                return ResourceManager.GetString("MessagesStatusReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حاله التنبيه.
        /// </summary>
        public static string MessageStatues
        {
            get
            {
                return ResourceManager.GetString("MessageStatues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نوع الارسال.
        /// </summary>
        public static string MessageType
        {
            get
            {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تقرير الاداء.
        /// </summary>
        public static string PerformanceReport
        {
            get
            {
                return ResourceManager.GetString("PerformanceReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدد دعوات التأهيل.
        /// </summary>
        public static string QualificationCount
        {
            get
            {
                return ResourceManager.GetString("QualificationCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدد دعوات التأهيل (قائمة).
        /// </summary>
        public static string QualificationCountList
        {
            get
            {
                return ResourceManager.GetString("QualificationCountList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تقرير حجم الانفاق بحسب النشاطات.
        /// </summary>
        public static string ReportSpendingBySpendActivities
        {
            get
            {
                return ResourceManager.GetString("ReportSpendingBySpendActivities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تقرير حجم الانفاق بحسب فئات الانفاق.
        /// </summary>
        public static string ReportSpendingBySpendAgency
        {
            get
            {
                return ResourceManager.GetString("ReportSpendingBySpendAgency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تقرير حجم الانفاق بحسب فئات الانفاق.
        /// </summary>
        public static string ReportSpendingBySpendCategory
        {
            get
            {
                return ResourceManager.GetString("ReportSpendingBySpendCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حجم الانفاق.
        /// </summary>
        public static string SizeOfSpending
        {
            get
            {
                return ResourceManager.GetString("SizeOfSpending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رساله للجوال.
        /// </summary>
        public static string SMS
        {
            get
            {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بند الانفاق.
        /// </summary>
        public static string Spendingitem
        {
            get
            {
                return ResourceManager.GetString("Spendingitem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بنود الانفاق.
        /// </summary>
        public static string Spendingitems
        {
            get
            {
                return ResourceManager.GetString("Spendingitems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to وقت البدء.
        /// </summary>
        public static string StartDate
        {
            get
            {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تقرير المنافسات.
        /// </summary>
        public static string TenderReport
        {
            get
            {
                return ResourceManager.GetString("TenderReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to قيمةالترسية.
        /// </summary>
        public static string TheValueOfTheAward
        {
            get
            {
                return ResourceManager.GetString("TheValueOfTheAward", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الفائز بالترسة.
        /// </summary>
        public static string TheWinnerOfthePromotion
        {
            get
            {
                return ResourceManager.GetString("TheWinnerOfthePromotion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البند الأعلى انفاق.
        /// </summary>
        public static string TopItemSpend
        {
            get
            {
                return ResourceManager.GetString("TopItemSpend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مقدار الوفورات الإجمالي.
        /// </summary>
        public static string TotalAmountOfSavings
        {
            get
            {
                return ResourceManager.GetString("TotalAmountOfSavings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مجموع المنافسات التي تمت الموافقة على طرحها.
        /// </summary>
        public static string TotalCountTheTendersApproved
        {
            get
            {
                return ResourceManager.GetString("TotalCountTheTendersApproved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مجموع المنافسات التي تم رفض على الطرح.
        /// </summary>
        public static string TotalCountTheTendersRejected
        {
            get
            {
                return ResourceManager.GetString("TotalCountTheTendersRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مجموع المنافسات التي تم إعادتها للتعديل.
        /// </summary>
        public static string TotalCountTheTendersReturned
        {
            get
            {
                return ResourceManager.GetString("TotalCountTheTendersReturned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مجموع المنافسات التي تمت مراجعتها.
        /// </summary>
        public static string TotalCountTheTendersReviewed
        {
            get
            {
                return ResourceManager.GetString("TotalCountTheTendersReviewed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدد المنافسات التي تمت تحويلها للمختص المستوى الثاني.
        /// </summary>
        public static string TotalCountTheTendersTransferredToUnitSpecialistLevel2
        {
            get
            {
                return ResourceManager.GetString("TotalCountTheTendersTransferredToUnitSpecialistLevel2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مجموع القيمه التقديرية.
        /// </summary>
        public static string TotalEstimatedValue
        {
            get
            {
                return ResourceManager.GetString("TotalEstimatedValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إجمالي قيمة المبيعات.
        /// </summary>
        public static string TotalPurchasedValue
        {
            get
            {
                return ResourceManager.GetString("TotalPurchasedValue", resourceCulture);
            }
        }
    }
}
